### ISSUE TITLE
Support for ROW_NUMBER() OVER ([PARTITION BY] ORDER BY)

### ISSUE THREAD

**Issue by drabastomek** [BlazingDB/blazingsql#1008]
**Is your feature request related to a problem? Please describe.**
This feature can be used to quickly remove duplicates from a table.

**Describe the solution you'd like**
`ROW_NUMBER() OVER...` should be an easy and a SQL standard way of removing duplicates from a table. For now I'm using `.drop_duplicates(subset=...)` from `cudf`.

**Describe alternatives you've considered**
Using `.drop_duplicates()` from `cudf`.

**Additional context**

**----For BlazingSQL Developers----**
**How and where should this be implemented?**
What part of the code should be feature be implemented? What should the APIs and/or classes look like?

**Other design considerations **
What components of the engine could be affected by this? What functions should we make sure we use/reuse?

**Testing considerations?**
What sort of unit tests and/or End to End tests be implemented to test this?

**Comment by williamBlazing** [comment]
We dont have support for window functions yet

**Comment by drabastomek** [comment]
I thought I just put it here so we have a trace 👍
