### ISSUE TITLE
[BUG] relative paths don't work with wild card

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingsql#1032]
```
from blazingsql import BlazingContext
bc = BlazingContext()
bc.create_table("etf",'/jupyterhub-homes/33/data/*.csv')
```

this works but if we  try

```
bc.create_table("etf",'data/*.csv')
```
It does not. It seems to be trying to append :// to the begining of the path which is incorrect since htat would assume root.

**Comment by Christian8491** [comment]
@felipeblazing could you share what exactly error you are seeing? 
As I know paths are always absolute,  right? 

`bc.create_table("etf",'data/*.csv')   # relative path`
