### ISSUE TITLE
[BUG] Calcite interprets timestamp as VARCHARS 

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingsql#1033]
If you read a cudf that stores a timestamp type calcite treats it as a varchar instead of a date so you cant apply date functions to it unles syou cast it. this is annoying and cumbersome

**Comment by Christian8491** [comment]
@felipeblazing do you have a special data for it? I just tried using `orders` table (from `tpch` dataset), but didn't replicate this issue. Both queries work well.

```
from blazingsql import BlazingContext
import cudf

bc = BlazingContext()

cudf_df = cudf.read_orc('/home/christian/blazingbd/dataset/100MB2Part/tpch/orders_0_0.orc')
# o_orderdate --> datetime64[ns]

bc.create_table('orders', cudf_df)
query = "select o_orderkey, EXTRACT(YEAR FROM o_orderdate) from orders"
query = "select * from orders where o_orderdate > TIMESTAMP '1995-09-05 17:00:00' limit 10"
result = bc.sql(query)
```

**Comment by williamBlazing** [comment]
Issue was traced to the csv_reader inferencing a timestamp as a string
