### ISSUE TITLE
[BUG] Latest code require boost 1.74 but should only require boost 1.72

### ISSUE THREAD

**Issue by esoha-nvidia** [BlazingDB/blazingsql#1037]
**Describe the bug**
A nightly version of cudf inadvertantly depended on boost 1.74.  This was reverted and latest cudf is now back to depending upon boost 1.72.  In the meantime, a blazingsql nightly was created that used that mistaken cudf and the new dependency clashes with the latest cudf.

**Steps/Code to reproduce bug**
The [list of conda releases](https://anaconda.org/blazingsql-nightly/blazingsql/files) here is used to generate the two URLs below.
1. Examine the dependencies of the latest nightly and notice that it requires boost 1.74.
    ```
    wget 'https://anaconda.org/blazingsql-nightly/blazingsql/0.16.0a/download/linux-64/blazingsql-0.16.0a-cuda10.2_py37_52.tar.bz2'
    tar xvjf blazingsql-0.16.0a-cuda10.2_py37_52.tar.bz2
    ldd lib/libblazingsql-engine.so  | grep boost
    ````
2. Examine the dependencies of the previous nightly and notice that it requires boost 1.72.
    ```
    wget 'https://anaconda.org/blazingsql-nightly/blazingsql/0.16.0a/download/linux-64/blazingsql-0.16.0a-cuda10.2_py37_25.tar.bz2'
    tar xvjf blazingsql-0.16.0a-cuda10.2_py37_25.tar.bz2
    ldd lib/libblazingsql-engine.so  | grep boost
    ````

**Expected behavior**
blazingsql should continue to depend on boost 1.72

**Environment overview (please complete the following information)**
 - Method of cuDF install: conda

**Comment by williamBlazing** [comment]
Thanks @esoha-nvidia a new conda package is available that no longer requires boost 1.74
