### ISSUE TITLE
[FEA] create_table(...) seamlessly from a partitioned parquet file

### ISSUE THREAD

**Issue by drabastomek** [BlazingDB/blazingsql#1047]
**Is your feature request related to a problem? Please describe.**
Currently, it's not possible to read a partitioned parquet file, even if the `partitions` and `partition_schema` parameters are specified.

**Describe the solution you'd like**
Ideally, it'd be great to default to `create_table('foo', 'data/bar.parquet/')` without specifying any additional parameters and read all the parquet files that might also be inside folders e.g. `data/bar.parquet/partition_idx=0/asdfjlghhs4.parquet` and `data/bar.parquet/partition_idx=1/asdfdf4234.parquet`

**Describe alternatives you've considered**
As a first step - I'd be happy with specifying the `partitions` and `partition_schema`.

**Additional context**
My current workaround results creating a large list of paths that I then pass to the `create_table(...)`. Like

```
transactions_partitions_cnt = 40
transactions_path = 's3://boo/data/bah.parquet/partition_idx={partition}/'
transactions_parq = [transactions_path.format(partition=p) for p in range(transactions_partitions_cnt)]
```

**----For BlazingSQL Developers----**
**How and where should this be implemented?**
This should be a part of the `create_table(...)` call.

**Other design considerations**
Python side implementation.

**Testing considerations?**
A unit test for testing a file that was saved from a cudf (single `.parquet` file), partitioned file save from cudf, dask_cudf and spark should be tested.

**Comment by williamBlazing** [comment]
@drabastomek Can you explain what you mean by:
Currently, it's not possible to read a partitioned parquet file, even if the partitions and partition_schema parameters are specified.
Does not work for you? https://docs.blazingdb.com/docs/apache-hive#advanced-usage-querying-a-hive-table-without-a-hive-cursor

I understand the ideal to being able to do it without needing to specify the partitions or the partitions_schema. We should probably pursue that, but I wanted to know if the feature we do have for that right now is not working as expected.

**Comment by drabastomek** [comment]
Hey! Yeah, when I tried it with the `partitions` flag specified it was complaining that this parameter can be only used to connect to Hive tables. I have not tested it with 0.16 though yet so might give it a go tonight and circle back.

**Comment by felipeblazing** [comment]
To implement this we need to make it so that bc.create_table can detect that this is the case. Namely that we have created a table on a directory where all of the contents are directories that have the format `attribute=value`. We will have to infer the types from the data but with this pattern we could go down the tree until we find the files we need to read and add this information as if the user had manually defined the partion values for the different files.
