### ISSUE TITLE
Dask does not know when we crash

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingsql#1049]
When we run .sql() and return_futures=false as is the default we wait to gather all of the results. Instead of that what we need to do is wait for them all to be complete while we chekc on their status. If any of them are failed we need to fail the query and throw an error, if they all finish  then we can proceed to gather the results.

but we should do this by viewing the futures.
 somethingn kind of like this
```
                query_done = False                
                while not query_done:
                    worker_id = 0
                    found_pending = False
                    for cur_future in dask_futures:
                        if cur_future.status == 'error' :
                            raise Exception("Worker " + str(self.nodes[worker_id]['worker']))
                        if cur_future.status == 'pending':
                            found_pending = True
                        worker_id = worker_id + 1
                    query_done = not found_pending

```

**Comment by jeanp413** [comment]
we just need to set `export DASK_DISTRIBUTED__SCHEDULER__ALLOWED_FAILURES=0` and the `dask_client.gather` will throw and exception when a worker die
