### ISSUE TITLE
[BUG] table name is "created" when should not

### ISSUE THREAD

**Issue by Christian8491** [BlazingDB/blazingsql#1061]
**Describe the bug**
When `create_table('fake_table', "/bath/path/to/data/") ` crash for some reason, the `fake_table` is still considered.

**Steps/Code to reproduce bug**
Uploading image. In a python script maybe you can't reproduce this

**Expected behavior**
`bc` should only contains tables that were created well.
![bad_created_table](https://user-images.githubusercontent.com/20308634/95117739-af7be100-070e-11eb-932c-7f25967b99ed.png)

**Comment by jeanp413** [comment]
@Christian8491 I cannot repro, can you test it again and conform it and if so do you have repro steps?

**Comment by Christian8491** [comment]
Maybe was fixed by this PR https://github.com/BlazingDB/blazingsql/pull/1071. In any case I will try to repro again. I will let you know.  @jeanp413

**Comment by Christian8491** [comment]
@jeanp413 I just verified that the issue go away! So, closing this issue.
