### ISSUE TITLE
Create tests for queries with partitioned data

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#1072]
We want to test this feature:
https://docs.blazingdb.com/docs/apache-hive#advanced-usage-querying-a-hive-table-without-a-hive-cursor

```
location='hdfs://localhost:54310/user/hive/warehouse/fin_transactions'

# This is the same table as the 'asia_transactions' example above, but without using the hive cursor
bc.create_table('asia_transactions2', location, 
                file_format='parquet', 
                hive_table_name='fin_transactions', 
                partitions = {'t_year':[2017, 2018], 
                              't_company_id':[2, 4, 6], 
                              'region': ['asia']}, 
                partitions_schema = [('t_year','int'),
                                     ('t_company_id','int'),
                                     ('region','str')])
```

In this example there is a table comprised of several folders:
The root folder in this example is `hdfs://localhost:54310/user/hive/warehouse/fin_transactions/` but lets refer to it as `/root_path/` for simplicity. So our table will then be comprised of the following folders:
`/root_path/t_year=2017/t_company_id=2/region=asia/`
`/root_path/t_year=2017/t_company_id=4/region=asia/`
`/root_path/t_year=2017/t_company_id=6/region=asia/`
`/root_path/t_year=2018/t_company_id=2/region=asia/`
`/root_path/t_year=2018/t_company_id=4/region=asia/`
`/root_path/t_year=2018/t_company_id=6/region=asia/`

The table will have all the columns for the files in those folders (should all have the same schema) but additionally the table has the following extra columns: t_year, t_company_id, region

We need to be able to test for all data types (or most).

**Comment by diegodfrf** [comment]
API
``` python
create_hive_partition_data(input, table_name, partitions, output, num_files_per_parquet)
test_hive_partition_data(input, table_name, partitions, partitions_schema, output, num_files_per_parquet=1):
```
`create_hive_partition_data` creates hive partitioned data folder structure, accepts number of files per parquet and multiple partitions.
`test_hive_partition_data` create and test with `bc.create_table` that the created folder structure is read correctly.

**Example**
``` python
test_hive_partition_data(
                input=("%s/%s_[0-9]*.%s") % (dir_data, "orders", ext),
		table_name='orders',
		partitions={
			'o_orderpriority': ['1-URGENT', '2-HIGH', '3-MEDIUM', '4-NOT SPECIFIED', '5-LOW'],
			'o_orderstatus': ['F', 'O', 'P'],
			'o_shippriority': [0]},
		partitions_schema=[('o_orderpriority', 'str'),
		                    ('o_orderstatus', 'str'),
		                    ('o_shippriority', 'int')],
		output='/path',
		num_files_per_parquet=4)
```
