### ISSUE TITLE
boolean test intermittent fail

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#1075]
test 09 of the boolean tests sometimes fails

**Comment by Christian8491** [comment]
I tried to reproduce this but I couldn't in multiple times, at least 10 times for both single node and distributed (2 workers)  using the `branch-0.17`

**Comment by rommelDB** [comment]
@Christian8491 Did you try in debug mode? I think some unnoticed bugs should appear in this way.

**Comment by Christian8491** [comment]
@rommelDB I will try, then.

**Comment by Christian8491** [comment]
The same. I couldn't reproduce this issue.

**Comment by williamBlazing** [comment]
An issue has been files with cudf https://github.com/rapidsai/cudf/issues/6733

**Comment by williamBlazing** [comment]
This issues was resolved in cudf
