### ISSUE TITLE
[DOC] Update blazing docs with ORC params and S3

### ISSUE THREAD

**Issue by Christian8491** [BlazingDB/blazingsql#1080]
## Report incorrect documentation
Here https://docs.blazingdb.com/docs/apache-orc there are two parameters that should be updated in order to be in the same line as `cudf.to_orc(`)  function, these are: `skip_rows` and `stripe`. Both they should be updated to `skiprows` and `stripes` as https://github.com/rapidsai/cudf/blob/branch-0.17/python/cudf/cudf/io/orc.py#L27 

The another one is here https://docs.blazingdb.com/docs/s3 the parameter `kms_key_amazon_resource` should be updated to `kms_key_amazon_resource_name` as the real name is, when `bc.s3()` is called.

**Comment by drabastomek** [comment]
I submitted the changes to the docs. Will close this once merged.

**Comment by drabastomek** [comment]
The changes have been merged. Closing.
