### ISSUE TITLE
[FEA] Optionally setting a Blazing local logging directory

### ISSUE THREAD

**Issue by rommelDB** [BlazingDB/blazingsql#1083]
**Is your feature request related to a problem? Please describe.**
If we run a script with a remote dask client attached to a Blazing Context and we pass a path to the  BLAZING_LOGGING_DIRECTORY config option. An error will raised if the folder passed don't exists on the client machine. A workaround consists of creating the same folder locally. But, it will depend on whether we have the required privileges to make it.

**Describe the solution you'd like**
If we are not able to create a folder, let's say because we lack privileges. We should pass another config option, for example, BLAZING_LOCAL_LOGGING_DIRECTORY pointing to a folder locally accessible.

**Comment by williamBlazing** [comment]
Can you describe how and when this issue arose for you?

**Comment by rommelDB** [comment]
Basically, that issue arose within a Docker environment. Each container had its own dask scheduler, and for example, the folder that would contain the logs was /usr/local/logs. So the python script that runs on a client machine outside of any container should set up config_options = {'BLAZING_LOGGING_DIRECTORY': '/usr/local/logs/'}. However, the path /usr/local/logs had write permissions within the containers (this is OK) but in the client machine the script was run with a normal user without administrator permissions to create such folder. @williamBlazing
