### ISSUE TITLE
Unit tests for UriDataProvider

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#1087]
We want to build unit tests for the UriDataProvider. 

The unit tests will need to create folders and test files in a tmp location for the unit tests to run.

The test suite should contain for following tests:
Test for empty folder
Test for folder with one file
Test for folder with multiple files
Test for folder with multiple files and one empty folder 
Test for folder with multiple files and one non-empty folder 
Test for folder with multiple folder, each with a couple files 
Test for wildcard that returns nothing 
Test for wildcard that returns one file 
Test for wildcard that returns multiple files 

For each of these we should test with and without ignore_missing_paths = True

Another set of tests should include setting `std::vector<std::map<std::string, std::string>> uri_values`

**Comment by williamBlazing** [comment]
For the set of tests that use `std::vector<std::map<std::string, std::string>> uri_values`
We want to always run it with  ignore_missing_paths = True
We will want to test the following:
one folder with multiple files, one folder with one file and one folder with no files

**Comment by diegodfrf** [comment]
Implemented in PR #1090
