### ISSUE TITLE
[BUG] Jupyter - Failed opening file blazing_log/RAL.0.log for writing: Permission denied

### ISSUE THREAD

**Issue by lmeyerov** [BlazingDB/blazingsql#1106]
**Describe the bug**

In a notebook environment, we get error `Failed opening file blazing_log/RAL.0.log for writing: Permission denied`, though `cudf` imports + computes fine

**Steps/Code to reproduce bug**

```
from blazingsql import BlazingContext
bc = BlazingContext()
```

Yields 

```
---------------------------------------------------------------------------
InitializeError                           Traceback (most recent call last)
<ipython-input-18-7813b5513ccc> in <module>
      1 from blazingsql import BlazingContext
----> 2 bc = BlazingContext()

/conda/envs/rapids/lib/python3.7/site-packages/pyblazing/apiv2/context.py in __init__(self, dask_client, network_interface, allocator, pool, initial_pool_size, maximum_pool_size, enable_logging, config_options)
   1423                 enable_logging=enable_logging,
   1424                 config_options=self.config_options,
-> 1425                 logging_dir_path=logging_dir_path,
   1426             )
   1427             node = {}

/conda/envs/rapids/lib/python3.7/site-packages/pyblazing/apiv2/context.py in initializeBlazing(ralId, networkInterface, singleNode, allocator, pool, initial_pool_size, maximum_pool_size, enable_logging, config_options, logging_dir_path)
    208         initial_pool_size,
    209         maximum_pool_size,
--> 210         enable_logging,
    211     )
    212 

/conda/envs/rapids/lib/python3.7/site-packages/bsql_engine/io/io.pyx in cio.initializeCaller()

/conda/envs/rapids/lib/python3.7/site-packages/bsql_engine/io/io.pyx in cio.initializeCaller()

/conda/envs/rapids/lib/python3.7/site-packages/bsql_engine/io/io.pyx in cio.initializePython()

InitializeError: [Initialize Error] Failed opening file blazing_log/RAL.0.log for writing: Permission denied

```

Also of interest, from Python 3 in the container running jupyter,  (variant of https://hub.docker.com/r/graphistry/graphistry-forge-base with `source activate rapids`), we see:

```
(rapids) graphistry@f7f4c4bf923e:~$ python
Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> from blazingsql import BlazingContext
>>> bc = BlazingContext()
listening: tcp://*:24031
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/conda/envs/rapids/lib/blazingsql-algebra.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
BlazingContext ready
```

I believe we have C++ protobufs enabled wrt above.

**Environment overview (please complete the following information)**

Above docker, rapids/blazing 0.16 , cuda 10.2. 

**Environment details**
Please run and paste the output of the `print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**----For BlazingSQL Developers----**
**Suspected source of the issue**
Where and what are potential sources of the issue

**Other design considerations**
What components of the engine could be affected by this?

**Comment by williamBlazing** [comment]
@lmeyerov we have had some similar issues in the past soon which we are hoping to resolve with this PR https://github.com/BlazingDB/blazingsql/pull/1110/files

With this PR you can set the directory for the logs files using the config options:
BLAZING_LOCAL_LOGGING_DIRECTORY and BLAZING_LOGGING_DIRECTORY

**Comment by lmeyerov** [comment]
@williamBlazing  Thanks!!

For a workaround in an 0.16 actually-stable release, maybe there's something we can do like create a logging stub file/folder somewhere or set the permissions on it somehow?

**Comment by williamBlazing** [comment]
@lmeyerov in 0.16 you should be able to set `BLAZING_LOGGING_DIRECTORY` which you could point it to a folder that you have set permissions for. That could resolve the issue for you now, if not then the issue would be resolved by the PR mentioned above

**Comment by lmeyerov** [comment]
Hmm we're struggling to reproduce now. Super strange, as this was all on clean containers. Happy to close, and report back if we see it again..
