### ISSUE TITLE
[DOC] Add ROUND to the documentation

### ISSUE THREAD

**Issue by beckernick** [BlazingDB/blazingsql#1116]
It looks like the operation ROUND was added in https://github.com/BlazingDB/blazingsql/pull/393 , but when I look for ROUND in the [docs](https://docs.blazingdb.com/docs/functions) I don't see any reference to it. It also does not come up in the search. Would be a nice addition to have this in the documentation as well

**Comment by drabastomek** [comment]
Added ROUND to docs and updated demo notebooks: [PR #36 to Welcome_to_BlazingSQL_Notebooks](https://github.com/BlazingDB/Welcome_to_BlazingSQL_Notebooks/pull/36)
