### ISSUE TITLE
Partition/Cluster/Bucket Keys like Hive

### ISSUE THREAD

**Issue by rsdpyenugula** [BlazingDB/blazingsql#112]
**Why we need to have Key's  to the table ?**
* As we all know not all the time you scan the whole table we may sometimes just look at the incremental load for which we need to apply a (sub) partitions key to the table. 
* In the distributed world it good to have  the sort key options within the worker and global which  give the developer an option for optimization

**Describe the solution you'd like**
Look at the Hive implementation.

**Comment by felipeblazing** [comment]
See https://github.com/BlazingDB/blazingdb-ral/issues/205. We will be adding the ability to directly query hive tables. If you follow that issue thats the one that we will be updating more frequently. As for data that is partitioned. If your file format has meta data like parquet or orc then our data skipping process will skip over that information anyway if it is not needed to process the query. You can track the progress of that PR here https://github.com/BlazingDB/blazingdb-ral/pull/142

**Comment by williamBlazing** [comment]
@rsdpyenugula In the near term, we are currently not planning on giving users the control over how queries get distributed. We have recently implemented predicate push down (data-skipping) that will enable not loading data that does not need to be loading.
