### ISSUE TITLE
Dynamic Resource Allocation

### ISSUE THREAD

**Issue by rsdpyenugula** [BlazingDB/blazingsql#113]
Not sure Dask has a way to specify the number of worked / maximum memory to be used for a  job or not if so inherit then and apply then at the Query level. This means for every query we should have the option to limit workers and memory.

Recommended Modes
1)  Fixed Mode 
    In this  mode Workers / Memory / both are  fixed  per process 
2) Step Mode
   In this mode  Workers / Memory / both can have a range of values (lower and higher ) and Step value. Using  the  step value it should  increment to  the   higher  range
4) Auto Mode
   It just runs the Step Mode with some default values or with the size of the data that needs  to be processed and available resources.

**Comment by felipeblazing** [comment]
Blazing Interfaces with dask for input and output but is not being run by dask. The scheduler and workers dask has have no control over how blazing operates. Blazing for now only has an auto mode. There is a pr which enables Paging but right now we do not plan on having the user be able to limit the amount of memory a query  might use in the near future though we see the benefit for many use cases.
