### ISSUE TITLE
Code refactoring and clean up

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#1131]
In the interest of making the code base better organized and friendlier to outside developers I recommend the following refactoring suggestions:

1. Move most if not all code of the possible code off of header files and properly place them in the .cpp and .cu files
2. ~~Break up files so that there is only one class per file and the file has the same name as the class. Classes that are all the same implementation of one base class should go into the same folder. Similarly for classes that are only used inside a particular class, should also go into the same folder~~ ( we wont do this)
3. Merge comms, engine and io into one same project. It no longer really makes sense nor help to have them in separate projects. It even causes horrible situations such as having two completely separate implementations of BlazingThread (they are just copies of each other, but this is an abomination)
4. Reorganize the files and folder of the code base. In particular in pyblazing there should not be a apiv2 folder and all that that entails
5. Remove any dead code (including commented out dead code)

Lower priority
6. Improve namespaces
7. Remove and organize includes

**Comment by williamBlazing** [comment]
proposed code organization

engine/src  would now hold most of the engine code (no more io and comms)

- bmr (same)
- communication (same but add the following: folder Network from io/src/Library/Network)
- transport (moved from comms/include/transport, comms/src/blazingdb/transport and also add comms/include/network/TCPSocket.h)
- cython (same)
- distribution folder becomes distribution_utils
- execution_graph 
    graph.h cpp
    kpair.h
    port.h
    PhysicalPlanGenerator.h    
    Context.h (currently its in comms/include/manager)
- execution_kernels
    kernel.h cpp
    kernel_type
    distribution_kernel
    BatchXXXXXXProcessing (these should be further broken down into individual files)
    LogicalFilter (some of this could go into operators)
    LogicalProject
- cache_machine
    CacheData
    GPUCacheData
    CPUCacheData
    HostCacheData
    WaitingQueue
    CacheMachine
    ConcatenatingCacheMachine
    cache_machine_config?
- BlazingTable
    BlazingTable
    BlazingTableView
    BlazingColumn
    BlazingColumnView
    BlazingColumnOwner
    BlazingHostTable
    
- Interpreter (same)
- io (same)
- operators (same)
- parser (same but add CalciteExpressionParsing and CalciteInterpreter)
- skip_data (same)
- utilities (same but add CodeTimer.h also add io/Util contents)
- ExeceptionHandling (moved over from io, add to it error.hpp)
- Logging (contains what used to be in io/Library/Logging)
- FilesReaders (same from io)
- FileSystem (same from io add to it BlazingContext from io/src/Config  but rename it to FileSystemContext its current name is very confusing)

**Comment by felipeblazing** [comment]
> In the interest of making the code base better organized and friendlier to outside developers I recommend the following refactoring suggestions:
> 
> 1. Move most if not all code of the possible code off of header files and properly place them in the .cpp and .cu files

Yup this is a good idea
> 2. Break up files so that there is only one class per file and the file has the same name as the class. Classes that are all the same implementation of one base class should go into the same folder. Similarly for classes that are only used inside a particular class, should also go into the same folder

There is no point to making such an arbitrary declartion. This is a poor idea as many files contain something like a base class and then 2 or 3 implementations of htat base class many times the classes themselves based on the ones above it. I do not see a need to seperate out thing arbitrarily and would rather see specific suggestions as opposed to these kinds of rules.


> 3. Merge comms, engine and io into one same project. It no longer really makes sense nor help to have them in separate projects. It even causes horrible situations such as having two completely separate implementations of BlazingThread (they are just copies of each other, but this is an abomination)

BlazingThread could become a header only library that we include in the code bases or we could make a "CORE" version. I agree that comms is pretty much useless now and should be merged in. I believe io provides value on its own and could be used by projects that wanted to use the io libraries withour relying on the rest of Blazing.

> 4. Reorganize the files and folder of the code base. In particular in pyblazing there should not be a apiv2 folder and all that that entails

Specific suggestions should be made here. I agree with the one about apiv2

> 5. Remove any dead code (including commented out dead code)

cppcheck can be used to find some of this but it has many false positives. still it was better than the nothing we had before

> 
> Lower priority
> 6. Improve namespaces
we need specific suggestions
> 7. Remove and organize includes
also specific suggestions needed

**Comment by felipeblazing** [comment]
> proposed code organization
> 
> engine/src would now hold most of the engine code (no more io and comms)
> 
> * bmr (same)
> * communication (same but add the following: folder Network from io/src/Library/Network)
> * transport (moved from comms/include/transport, comms/src/blazingdb/transport and also add comms/include/network/TCPSocket.h)
this is actually dead code we dont use that anymore

> * cython (same)

same what?
> * distribution folder becomes distribution_utils
what does the word utils communicate in this sense? I almost feel like the word utils is often times a bit of an anti pattern

> * execution_graph
>   graph.h cpp
>   kpair.h
>   port.h
>   PhysicalPlanGenerator.h
>   Context.h (currently its in comms/include/manager)
> * execution_kernels
>   kernel.h cpp
>   kernel_type
>   distribution_kernel
>   BatchXXXXXXProcessing (these should be further broken down into individual files)
>   LogicalFilter (some of this could go into operators)
>   LogicalProject
> * cache_machine
>   CacheData
>   GPUCacheData
>   CPUCacheData
>   HostCacheData
I think a better refactoring here would be supplying the cachedata with a memory resource or take templated functions for caching or decaching. For example when we make GPUCacheDataWithMetdadata what we really want to say is something more like here is a cache data, the data is in gpu, it includes metadata, with both of these being able to be changed
>   WaitingQueue
>   CacheMachine
>   ConcatenatingCacheMachine
I dont see a purpose in sepearting out the cache machiens into seperate files
>   cache_machine_config?
??
> * BlazingTable
>   BlazingTable
>   BlazingTableView
>   BlazingColumn
>   BlazingColumnView
>   BlazingColumnOwner
>   BlazingHostTable
> * Interpreter (same)
> * io (same)
> * operators (same)
> * parser (same but add CalciteExpressionParsing and CalciteInterpreter)
> * skip_data (same)
> * utilities (same but add CodeTimer.h also add io/Util contents)
utilities to me really seems like a catch all for when we couldnt figure out where to put things. I would rather thigns be more explicit in terms of their purpose

> * ExeceptionHandling (moved over from io, add to it error.hpp)
I would rather move this and blazingthread to some core library.

**Comment by williamBlazing** [comment]
What do you mean a "core library" you mean creating a new project where we try to accumulate some "core" dependencies? This would create a new library. I am trying to reduce the number of projects and libraries and therefore some of the complexity out of our codebase.
If we really want to keep io separate (I dont agree we should), we could have that be the "core" and then only have two projects or libraries. io and engine. But honestly I really dont see the need. The idea that maybe we will want to use "it" separately in the future means you are imposing a complexity for some totally unknown possibility. And its a possibility with unknown requirements. I think if the possibility arises, then we pull out the necessary components at that point where we actually know the requirements, and until such a moment arrives, we have have out code in a simpler state

**Comment by williamBlazing** [comment]
I agree that we dont need to break up all files into one file per class. I can propose a new structure that is less aggressive.

In the structure proposal, when I say `(same)` i mean, leaving that the same as the current structure

`distribution folder becomes distribution_utils` i propose this only to indicate that there are no classes, just utility functions here

And as for the utils folder, yes it is a catch all. I just did not want to overengineer how and where we put the rest. I am ok with organizing the remainder in a better way, or we can leave it all in a catch all utilities folder

**Comment by felipeblazing** [comment]
> What do you mean a "core library" you mean creating a new project where we try to accumulate some "core" dependencies? This would create a new library. I am trying to reduce the number of projects and libraries and therefore some of the complexity out of our codebase.

Theres pros and cons. The pros of making it a separate library is reduced compile time and the ability to reuse these libraries in other projects. The cons you mention all seem to be related to duplicated code which is what this core library would solve.

> If we really want to keep io separate (I dont agree we should), we could have that be the "core" and then only have two projects or libraries. io and engine. But honestly I really dont see the need. The idea that maybe we will want to use "it" separately in the future means you are imposing a complexity for some totally unknown possibility. And its a possibility with unknown requirements. I think if the possibility arises, then we pull out the necessary components at that point where we actually know the requirements, and until such a moment arrives, we have have out code in a simpler state

Consider dask-sql for example. At some point I could envision the dask-sql project wanting to use the same i/o library as us if they wanted to support all the same file systems. Leaving these libraries as seperate opens up the door for more people to be reusing our code.

**Comment by felipeblazing** [comment]
> And as for the utils folder, yes it is a catch all. I just did not want to overengineer how and where we put the rest. I am ok with organizing the remainder in a better way, or we can leave it all in a catch all utilities folder

We could leave it as a catch all for now with the intent to some day put them im more appropriate places. Not all of the code in utils is used broadly in the engine.

**Comment by williamBlazing** [comment]
proposed code organization

engine/src  would now hold most of the engine code (no more io and comms)

- bmr (same)
- communication (same but add the following: folder Network from io/src/Library/Network)
- transport (moved from comms/include/transport, comms/src/blazingdb/transport and also add comms/include/network/TCPSocket.h)
- cython (same)
- distribution folder becomes distribution_utils
- execution_graph 
    graph.h cpp
    kpair.h
    port.h
    PhysicalPlanGenerator.h    
    Context.h (currently its in comms/include/manager)
- execution_kernels
    kernel.h cpp
    kernel_type
    distribution_kernel
    BatchXXXXXXProcessing 
    LogicalFilter 
    LogicalProject
- cache_machine
    CacheData (this should include GPUCacheData, CPUCacheData, HostCacheData)
    WaitingQueue
    CacheMachine (including    ConcatenatingCacheMachine)
- BlazingTable
    BlazingTable
    BlazingTableView
    BlazingColumn
    BlazingColumnView
    BlazingColumnOwner
    BlazingHostTable
    
- Interpreter (same)
- io (same)
- operators (same)
- parser (same but add CalciteExpressionParsing and CalciteInterpreter)
- skip_data (same)
- utilities (same but add CodeTimer.h also add io/Util contents)
- ExeceptionHandling (moved over from io, add to it error.hpp)
- Logging (contains what used to be in io/Library/Logging)
- FilesReaders (same from io)
- FileSystem (same from io add to it BlazingContext from io/src/Config  but rename it to FileSystemContext its current name is very confusing)

**Comment by williamBlazing** [comment]
Plan of attack:
- First lets get rid of the comms project 
- Lets start rearranging and refactoring the code to follow the new proposed organization except for all the execution kernel files, cacheMachine files and all the io project code. 
  - This rearranging and refactoring should be done in two passes. First we will move code from header files to implementation files and any other "cleaning" (removind dead code and stuff). Then in a separate PR we will move it to its new location in the proposed file organization.
- The last stage will be attacking the execution kernel files, cacheMachine files and io project code. This will be done after the comms refactor is done.
