### ISSUE TITLE
Add SQRT, STDDEV, and VAR to the docs

### ISSUE THREAD

**Issue by derekmorr** [BlazingDB/blazingsql#1157]
Calcite provides built-in support for the `SQRT`, `STDDEV_SAMP`, `STDDEV_POP`, `VAR_SAMP`, and `VAR_POP` functions. The BlazingSQL docs should be updated to include these functions.

Reproducible example (using app.blazingsql.com with the RAPIDS Stable kernel):

```python
import pandas as pd
from blazingsql import BlazingContext

df = pd.DataFrame({'A' : range(1, 10000000, 1)})
bc = BlazingContext()
bc.create_table('tbl', df)

query = """
SELECT
  STDDEV_SAMP(A) AS std_dev_samp,
  STDDEV_POP(A) as std_dev_pop,
  VAR_SAMP(A) AS var_samp_a,
  VAR_POP(A) AS var_pop_a
FROM tbl
"""
bc.explain(query)
bc.sql(query)

bc.sql("SELECT SQRT(A) AS sqrt_a FROM tbl")
```

**Comment by felipeblazing** [comment]
Holy smokes it sure does work! I was surprised the plan didn't require any operators we hadn't already implemented.

**Comment by beckernick** [comment]
Looks like VAR and STDDEV have been added, but SQRT may not be included yet.

https://docs.blazingdb.com/v0.17/docs/aggregators#variance-var_samp-var_pop

**Comment by williamBlazing** [comment]
I just added SQRT

**Comment by williamBlazing** [comment]
They have been added to 0.17 https://docs.blazingdb.com/v0.17/docs
