### ISSUE TITLE
[BUG] bc.create_table doesn't ignore headers on 2nd and subsequent files with multiple CSV

### ISSUE THREAD

**Issue by MurrayData** [BlazingDB/blazingsql#1159]
**Describe the bug**
bc.create_table doesn't ignore headers on 2nd and subsequent files with multiple CSV

**Steps/Code to reproduce bug**

Python code: 

```
from blazingsql import BlazingContext
import cudf
import glob

bc = BlazingContext()

BlazingContext ready
filepath = '/data/nsul/NSUL_OCT_2020*.csv'
files = sorted(glob.glob(filepath))
print(files)

['/data/nsul/NSUL_OCT_2020_EE.csv', '/data/nsul/NSUL_OCT_2020_EM.csv', '/data/nsul/NSUL_OCT_2020_LN.csv', '/data/nsul/NSUL_OCT_2020_NE.csv', '/data/nsul/NSUL_OCT_2020_NW.csv', '/data/nsul/NSUL_OCT_2020_SC.csv', '/data/nsul/NSUL_OCT_2020_SE.csv', '/data/nsul/NSUL_OCT_2020_SW.csv', '/data/nsul/NSUL_OCT_2020_WA.csv', '/data/nsul/NSUL_OCT_2020_WM.csv', '/data/nsul/NSUL_OCT_2020_YH.csv']

# create table nsul from Multiple CSV
bc.create_table('nsul', files)

query = ''' 
        SELECT uprn, pcds AS `postcode` 
        FROM nsul
        WHERE pcds <> 'pcds'
        ORDER BY `uprn`
        '''

nsul_hd = bc.sql(query)
```

Result:

uprn | postcode
-- | --
0 | pcds
0 | pcds
0 | pcds
0 | pcds
0 | pcds
... | ...
906700537284 | G1 5DT
906700537285 | G1 5DT
906700537286 | G20 6BQ
906700537287 | G53 7RZ
906700601612 | G20 7TB

39341783 rows × 2 columns

**Expected behavior**
The header rows should be ignored on all files.

**Environment details**
Dell T7910 1TB RAM 2x V100 with NVLink, NVMe RAID

**Additional context**
Workaround, SQL changed to ignore header rows with WHERE clause:

```
query = ''' 
        SELECT uprn, pcds AS `postcode` 
        FROM nsul
        WHERE pcds <> 'pcds'
        ORDER BY `uprn`
        '''

nsul_hd = bc.sql(query)

nsul_hd = bc.sql(query)
```

Result

uprn | postcode
-- | --
1 | BS1 5TR
26 | BS11 0YA
27 | BS11 0YA
30 | BS10 7RZ
31 | BS10 7RZ
... | ...
906700537284 | G1 5DT
906700537285 | G1 5DT
906700537286 | G20 6BQ
906700537287 | G53 7RZ
906700601612 | G20 7TB

39341772 rows × 2 columns

Screenshot of one of the input files. All are in identical format.

![image](https://user-images.githubusercontent.com/8914493/99279851-9b0c2780-2828-11eb-8d12-c8c1156ef1e2.png)

**Comment by Christian8491** [comment]
Hi @MurrayData as all your input files have `header`, you should use the `header=0` argument when creating the table to avoid reading these lines.
`bc.create_table('nsul', files, header=0)`
In order to avoid the aditional `WHERE` statement as a workaround.

**Comment by MurrayData** [comment]
> Hi @MurrayData as all your input files have `header`, you should use the `header=0` argument when creating the table to avoid reading these lines. In order to avoid the aditional `WHERE` statement as a workaround. So, basically call:
> 
> `bc.create_table('nsul', files, header=0)`

I tried that and it works. It's slightly confusing as the documentation implies that header=0 is the default so this would be expected behaviour with explicitly adding the parameter. There are 11 input files ,but without 'header=0', 10 of these are interpreted as data:

uprn | postcode
-- | --
0 | pcds
0 | pcds
0 | pcds
0 | pcds
0 | pcds
0 | pcds
0 | pcds
0 | pcds
0 | pcds
0 | pcds
0 | pcds
1 | BS1 5TR
26 | BS11 0YA
27 | BS11 0YA
30 | BS10 7RZ
31 | BS10 7RZ
32 | BS11 0QL
33 | BS11 8AF
34 | BS11 8AF
38 | BS11 8AF

If I explicitly add the parameter:

	uprn	postcode
0	1	BS1 5TR
1	26	BS11 0YA
2	27	BS11 0YA
3	30	BS10 7RZ
4	31	BS10 7RZ
5	32	BS11 0QL
6	33	BS11 8AF
7	34	BS11 8AF
8	38	BS11 8AF
9	41	BS10 7RZ
10	42	BS1 5UU
11	43	BS11 8AT
12	44	BS11 9AG
13	45	BS11 8AT
14	46	BS11 8AT
15	47	BS11 8AT
16	48	BS11 8AT
17	49	BS11 9HS
18	53	BS11 8AB
19	54	BS11 8AE

So I think it is still a bug in that the default parameter is not being carried through to subsequent files.
