### ISSUE TITLE
if support Multi machine multi Graphic card

### ISSUE THREAD

**Issue by cmdares** [BlazingDB/blazingsql#116]
Our data center has 20 servers, each with 4 Graphic cards.
Can we build one cluster and make full use of all resources (80 NV 2080ti )?  to support maximum parallelism.
Thanks!

**Comment by felipeblazing** [comment]
Yes you can. If you want to get help getting a cluster set up you can reach out either via email, felipe@blazingsql.com or via the slack channel found at https://rapids-goai.slack.com in the channel called "blazingsql"

**Comment by felipeblazing** [comment]
We are working on simplifying the deployment process so that it can be entirely managed by dask but for now there are some manual things to run.

**Comment by williamBlazing** [comment]
@cmdares Our latest release makes deploying with multiple GPUs even easier. See here:
https://docs.blazingdb.com/docs/distributed
