### ISSUE TITLE
[FEA] Don't print pyblazing config, logging, or cluster info by default

### ISSUE THREAD

**Issue by beckernick** [BlazingDB/blazingsql#1169]
In the 2020-11-18 nightly conda package, when I create a blazingcontext with a dask cluster I get what looks like it may be debug output printed:

```
...
found config
blazing_log
{'tcp://$IP:32969': {'port': 27686, 'ip': '$IP'}, 'tcp://$IP:35113': {'port': 28652, 'ip': '$IP'}, ...}
```

The first two print statements come from here: https://github.com/BlazingDB/blazingsql/blob/1c814759eacbbced6908da012aa9148612effa59/pyblazing/pyblazing/apiv2/context.py#L1349-L1355

I'm not entirely sure where the worker info comes from, but I suspect it's here: https://github.com/BlazingDB/blazingsql/blob/1c814759eacbbced6908da012aa9148612effa59/pyblazing/pyblazing/apiv2/comms.py#L43-L45

Perhaps these might be switched to default off? With a large cluster, these can quickly add up.

**Comment by williamBlazing** [comment]
These should be taken out completely. Thanks for pointing this out
