### ISSUE TITLE
[FEA] Support INITCAP for strings

### ISSUE THREAD

**Issue by beckernick** [BlazingDB/blazingsql#1177]
I'd like to be able to use INITCAP to capitalize the first character of every "token" in a string. This is listed as a supported operation on string columns in the Calcite reference, but is currently not implemented.

```python
from pyspark.sql import SparkSession
from blazingsql import BlazingContext
import pandas as pd
​
​
# spark = SparkSession.builder \
#     .master("local") \
#     .getOrCreate()
​
# bc = BlazingContext()
​
​
df = pd.DataFrame({
    "a": ["this is", "an example", "of sql"],
    "b": [10, 9, 8],
})
​
bc.create_table("df", df)
sdf = spark.createDataFrame(df)
sdf.createOrReplaceTempView("df")
​
query = """
SELECT
    a,
    INITCAP(a)
FROM df
"""
​
spark.sql(query).show()
​
print(bc.explain(query))
# print(bc.sql(query)) # fails
+----------+----------+
|         a|initcap(a)|
+----------+----------+
|   this is|   This Is|
|an example|An Example|
|    of sql|    Of Sql|
+----------+----------+

LogicalProject(a=[$0], EXPR$1=[INITCAP($0)])
  BindableTableScan(table=[[main, df]], projects=[[0]], aliases=[[a, EXPR$1]])

```

**Comment by derekmorr** [comment]
I'm happy to work on this if no one else is interested.

**Comment by williamBlazing** [comment]
@derekmorr Welcome to the community! You are welcome to tackle this issue. I have assigned it to you. If you have any questions, please feel free to ask.

**Comment by williamBlazing** [comment]
The implementation of this feature should look a little like this https://github.com/BlazingDB/blazingsql/pull/1193

**Comment by derekmorr** [comment]
Just to clarify -- it looks like I have to first submit a PR to the tests repository with updated parquet files, then make a PR for this issue in this repo so that CI will run, is that correct?

**Comment by williamBlazing** [comment]
Hello @derekmorr that is correct. I am working on making some of our development processes public to help people such as yourself to help out more easily, but I have been too busy. You can take a look at this which is from our internal documents:

Adding new End to End tests
 
To add a new End to End tests you have to follow the next steps:
If the new query is related to an existing script, you can add it at the end of the script inside:
$CONDA_PREFIX/blazingsql/test/BlazingSQLTest/EndToEndTests/existingScript.py
In case that the new query is part of a non-existent test suite, create a new script and add the new tests on the new script inside:
$CONDA_PREFIX/blazingsql/test/BlazingSQLTest/EndToEndTests/newScript.py
 After you add the new queries, you have to export the next variable:
export BLAZINGSQL_E2E_EXEC_MODE="generator"
Then you need to up the drill instance.
Enter to $CONDA_PREFIX/blazingsql and execute: 
	./test.sh e2e tests=<new_suiteTest>
Enter to  $CONDA_PREFIX/blazingsql-testing-files/ and push the changes.
Push the changes related to new tests on the PR for blazingsql repo.
Make sure that all the GPU_CI tests are passing.
** If you added a new script, you have to add this also in allE2ETest.py
if runAllTests or ("newScriptTest" in targetTestGroups):
        newScriptTest.main(dask_client, drill, dir_data_file, bc, nRals)
