### ISSUE TITLE
[FEA] Enable dialect-specific operators with CalciteConnectionProperty

### ISSUE THREAD

**Issue by beckernick** [BlazingDB/blazingsql#1178]
Calcite [supports](https://calcite.apache.org/docs/reference.html#dialect-specific-operators) a variety of useful operators that are not in the SQL standard.

It appears these can be enabled by setting the `FUN` parameter of CalciteConnectionProperty for the connection.

https://calcite.apache.org/docs/adapter.html#jdbc-connect-string-parameters

This is necessary for:
- https://github.com/BlazingDB/blazingsql/issues/1173
- https://github.com/BlazingDB/blazingsql/issues/1174
- https://github.com/BlazingDB/blazingsql/issues/1176

**Comment by williamBlazing** [comment]
It may be as simple as adding mysql and/or postgres to this line https://github.com/BlazingDB/blazingsql/blob/branch-0.17/algebra/blazingdb-calcite-application/src/main/java/com/blazingdb/calcite/application/RelationalAlgebraGenerator.java#L120

I am not sure if this can cause any conflicts or issues if some operators have different syntax in different SQL variants, but its worth a try.

**Comment by beckernick** [comment]
Beyond running `./tests.sh`, should anything else be tested locally?
