### ISSUE TITLE
Install docker quickstart wrong port

### ISSUE THREAD

**Issue by robomotic** [BlazingDB/blazingsql#1208]
Hi guys,
reading this:
https://docs.blazingdb.com/docs/install-via-docker

The command should be:
sudo docker run --runtime=nvidia --rm -p 8888:8888 -p 8787:8787 -p 8786:8786 blazingdb/blazingsql:latest
instead of:
sudo docker run --runtime=nvidia --rm -p 8888:80 -p 8787:8787 -p 8786:8786 blazingdb/blazingsql:latest

Cheers.

**Comment by roaramburu** [comment]
I updated the docs, thank you for the help!
