### ISSUE TITLE
High memory usage on relatively small SQL query 

### ISSUE THREAD

**Issue by tbates1996** [BlazingDB/blazingsql#1209]
I'm facing an issue when trying to run a SQL query on my data. I'm currently running a g4db.8xlarge EC2 instance with a Telsa T4 and 128GB of RAM using CUDA 10.2. Im currently running BlazingSQL 0.16.1. 

Im am loading a few ~2GB (total 10GB) parquet files into a table and attempting to run a query on them. Im seeing that all of my GPU memory and then a large portion of my RAM are being consumed when this query is run. Dask distributed starts to continuously output a variation this line:
```
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 100.00 GB -- Worker memory limit: 133.55 GB
```

From here, it seems that my worker pauses or crashes and then the process hangs in my Jupyter notebook. I'm not sure why this much memory is being consumed since theoretically it could all fit on the GPU if it needed too. I think there might be a memory leak happening somewhere if I had to guess. 

This seems strange to me since the data is relatively small and I'm even seeing this issue for a `SELECT some_field FROM table` when trying to read in some data into memory.

**Comment by felipeblazing** [comment]
Can you share your code so we can more properly diagnose? 

I am guessing you are loading up the data with dask and it expands to much larger than its 2GB representation. If you are createing the tables directly from the files it might be something else.
 can you share the schema, just need the datatypes, and the number of rows per file?

**Comment by tbates1996** [comment]
We are creating the table directly from the parquet files. This is how our code looks right now:
```
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
# Params I've tried: threads_per_worker=1, memory_limit = "4GB", CUDA_VISIBLE_DEVICES = "0", device_memory_limit=0.6, n_workers=1, nanny = False)
cluster = LocalCUDACluster()
client = Client(cluster)

from blazingsql import BlazingContext
bc_cluster = BlazingContext(dask_client=client, network_interface='lo')

data_location = "/home/somefile/location"
bc_cluster.create_table(table_name, data_location)

# Not the actual query, but we are still failing to run this. 
ITEMS_SQL = '''
  SELECT 
  *
 FROM {}
'''

bc_cluster.sql(ITEMS_SQL)
```
Per file it would be around 28,000,000 rows
Data types of columns from running `.dtypes`:
```
object
datetime64[us]
datetime64[us]
int64
object
float64
float64
float64
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
int64
int64
float64
float64
float64
float64
float64
object
```

**Comment by felipeblazing** [comment]
If you look at the logs in the blazing_log directory there should be one called something like  RAL.0.log (one for each gpu). Do you see a message along the lines of 

```
Add to CacheMachine into GPU cache
Add to CacheMachine into CPU cache <-- its caching the data in ram because you dont have enough gpu memory
```

If this is the case you are probably using cpu cache when processing this query. That select * will return ALL of the files loaded up into GPU memory which given the fact that parquet is compressed would lead me to believe this would be much larger than the gpu memory available. If its 10GB parquet it might be 30GB or more uncompressed. You would need at least that much GPU memory if you wanted to return the entire thing as a gpu dataframe. You can still run queries on it but your results sets need to fit in gpu.

Try doing things like aggregating columns or filtering and joining and it should still be able to run queries much larger than gpu memory but the results need to fit.
