### ISSUE TITLE
Compatibility with Nvidia 30x series cards and ubuntu 20.04 is lacking

### ISSUE THREAD

**Issue by endomorphosis** [BlazingDB/blazingsql#1211]
The issue is that none of these dependencies will build for me for 2 reasons. 

First is that my graphics card is an Nvidia 3070, and the minimum driver installation is Nvidia-455.38, this is incompatible with the current build

Second is that I'm using Ubuntu 20.04, and the operating system support is limited to 16.04 and 18.04. 

I am using conda

**Comment by williamBlazing** [comment]
Hello @endomorphosis our support and compatibility is based on what `cudf` supports. If you would like to see support for ubuntu 20.04 I suggest you file an issue here https://github.com/rapidsai/cudf

As for the Nvidia 30x series, I dont see why it should not work. What version of CUDA do you have? You may need to run it with CUDA 11.

**Comment by roaramburu** [comment]
We do support those configs.
