### ISSUE TITLE
Support TRIM operation for string literals

### ISSUE THREAD

**Issue by ayushdg** [BlazingDB/blazingsql#1219]
**Is your feature request related to a problem? Please describe.**
The TRIM operator currently supports string columns only. As mentioned in https://github.com/BlazingDB/blazingsql/pull/1201#discussion_r530304895, it can be extremely useful for string literals as well.

**Describe the solution you'd like**
Add support for trimming string literals that potentially goes via the host.

```sql
SELECT TRIM(LEADING 'abc' FROM 'abcdef' )

output
------
def

```

One potential solution could be an option described here https://github.com/BlazingDB/blazingsql/pull/1201#discussion_r530591709

**Comment by williamBlazing** [comment]
@ayushdg  the feature you describe i think would only be useful for edge cases. See my comment here https://github.com/BlazingDB/blazingsql/issues/1222

Apache Calcite will usually perform operations on literals before the engine actually needs to do anything.

Given how many things we need that are higher priority, I am going to close this issue. If you see a situation where Calcite is not performing the operations on literals as expected, please create an issue again, and we can handle it then.

Thanks again!
