### ISSUE TITLE
[DOC] Add new string functionality to the docs

### ISSUE THREAD

**Issue by beckernick** [BlazingDB/blazingsql#1227]
The following string functionality has recently been added, but is not yet present in the documentation:

- LOWER
- LTRIM
- REPLACE
- RTRIM
- TRIM
- UPPER
- LEFT
- REVERSE
- RIGHT

**Comment by roaramburu** [comment]
https://docs.blazingdb.com/v0.17/docs/string-functions

**Comment by beckernick** [comment]
Ah, excellent :) 

I did not realize I was on the 0.16 docs. Thanks!

**Comment by roaramburu** [comment]
No worries, it's not all that obvious. Will need to look into that.
