### ISSUE TITLE
Brainstorm runtime engine execution visualization

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#1252]

**Comment by williamBlazing** [comment]
We want to provide some way for users to easily visualize what the engine is working on during runtime execution. Similar to dask's task stream UI.

Some of the key things a user will want to know is:
- What is the engine doing?
- Did the engine hang?
- Where are the bottlenecks, or where is most of the time being spent?
- Resource consumption summary

**Comment by williamBlazing** [comment]
what do we want to show?

progress info:
- bars for batches/rows processed for each step. bars changing color when finished. It could be a horizontal bar for each step and different segments in the bar for each node. Each segment would turn colors when each node completes

performance/bottleneck info:
- bars for time spent processing for each step. Perhaps expressed as a percentage

graph of device/cpu/disk memory consumption over time. Overlaid with limits

graph of messages? Want to show something here related to communication.

**Comment by williamBlazing** [comment]
Ideas on how to capture/stream the info.
We could use `cudf.read_csv` but we also use `byte_range` parameter to limit io and processing. We could collect the size of the log files before we start a query and that way, when we are reading the file over and over again, we are reading less.

We probably also dont want to be using the main RAL.X.log files for this. We will want to dial in what we capture and how.

**Comment by beckernick** [comment]
@quasiben @jakirkhim @vibhujawa @ayushdg I'd be very interested in your thoughts on this high-level topic of execution visualization as well

**Comment by jakirkham** [comment]
Would any of this make sense to add to the Dask dashboard? Asking since we are already discussing some changes there ( https://github.com/dask/distributed/issues/4260 ).
