### ISSUE TITLE
Improve Out of Memory error messages rather than hard crash 

### ISSUE THREAD

**Issue by chardog** [BlazingDB/blazingsql#1264]
**Is your feature request related to a problem? Please describe.**
When developing on a single GPU on a small memory server I found that if you exceeded the GPU and RAM you would simply get a crash. No warning or friendly error. Increase the RAM and it runs beautifully so the GPU spills over to use RAM.  

**Describe the solution you'd like**
I think for managing a production environment, or even for a nube developing for the first time, it would be nice to get some better error message feedback.

**Describe alternatives you've considered**

**Additional context**

**----For BlazingSQL Developers----**
**How and where should this be implemented?**
What part of the code should be feature be implemented? What should the APIs and/or classes look like?

**Other design considerations**
What components of the engine could be affected by this? What functions should we make sure we use/reuse?

**Testing considerations?**
What sort of unit tests and/or End to End tests be implemented to test this?

**Comment by rommelDB** [comment]
Fixed by #1255
