### ISSUE TITLE
Create manual dask workers per SSH session?

### ISSUE THREAD

**Issue by chardog** [BlazingDB/blazingsql#1265]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.blazingdb.com/docs/distributed
There is a code snippet:
# on one terminal
conda activate bsql
CUDA_VISIBLE_DEVICES=0 dask-worker 123.123.123.123:8786

# on another terminal
conda activate bsql
CUDA_VISIBLE_DEVICES=1 dask-worker 123.123.123.123:8786

# repeat for other GPUs

**Describe the problems or issues found in the documentation**
The text says "on one terminal" and "on another terminal".
On a single machine with 4 GPUs, do I need to log into separate SSH sessions 4 times to start the worker in each session?

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

**Comment by drabastomek** [comment]
Hey @chardog! 

From what I'm reading from your description, you have a single machine with 4 GPUs. Thus, in the documentation, you should refer to the section above the one  you are citing: [Single-node, multiple-gpu with localCUDACluster](https://docs.blazingdb.com/docs/distributed#single-node---multiple-gpu-with-localcudacluster). 

If you want to have a greater control over which/how many GPUs you want to assign to a cluster, I'd suggest checking this documentation page: [Dask CUDA: Specializations](https://dask-cuda.readthedocs.io/en/latest/specializations.html).

It is possible to use `dask-scheduler` and start individual `dask-cuda-worker` processes on a single machine in separate terminal windows but that seems like an overkill here.

**Comment by williamBlazing** [comment]
Hello @chardog unfortunatelly the description of the code and instructions you are running are not in the documentation link you provided. Perhaps you saw incorrect instructions in old documentation? If so we would love to know where those incorrect instruccions came from so that we can correct them.

**Comment by williamBlazing** [comment]
Closed due to lack of information. Please reopen if you have more information
