### ISSUE TITLE
Deadlock with Dask Multi GPUs [BUG]

### ISSUE THREAD

**Issue by chardog** [BlazingDB/blazingsql#1274]
**Describe the bug**
When running a python script multiple times simultaneously using 1 Dask worker on 1 GPU the script succeeds
When adding more workers (eg 4 workers in a 4 GPU server) the same script will hang due to a deadlock when you run it 3 4 5 times simultaneously. 

**Steps/Code to reproduce bug** 
Make a python script file using the NY Taxi dataset. 
sync-emi-gpu-test1/python/script/sample_taxi.py  (the python script code is below)

Download NY taxi data and save it in:
/sync-emi-gpu-test1/python/lastprocesseddata/sample_taxi.parquet
/sync-emi-gpu-test1/python/newdata/sample_taxi.parquet

Create these directories:
/sync-emi-gpu-test1/python/updates
/sync-emi-gpu-test1/python/deletes
/sync-emi-gpu-test1/python/inserts

Copy the entire folder structure to:
/sync-emi-gpu-test2
/sync-emi-gpu-test3 
/sync-emi-gpu-test4
/sync-emi-gpu-test5

fix the paths in the python scripts to reference the correct paths /sync-emi-gpu-test2 /sync-emi-gpu-test3 etc.

Run the sample_taxi.py one or more times simultaneously on a system with **1 worker on 1 GPU and it will succeed**. 

conda activate blazingnewversion
python /sync-emi-gpu-test1/python/script/sample_taxi.py &
python /sync-emi-gpu-test2/python/script/sample_taxi.py &
python /sync-emi-gpu-test3/python/script/sample_taxi.py &
python /sync-emi-gpu-test4/python/script/sample_taxi.py &
python /sync-emi-gpu-test5/python/script/sample_taxi.py &

Run the sample_taxi.py on a system with **4 workers (4 GPUs) and it will begin to deadlock when you run it 3,4,5 times at same time.** 
Using bash script:
source ~/anaconda3/etc/profile.d/conda.sh
export -f conda
export -f __conda_activate
export -f __conda_reactivate
export -f __conda_hashr
conda activate blazingnewversion
python /sync-emi-gpu-test1/python/script/sample_taxi.py &
python /sync-emi-gpu-test2/python/script/sample_taxi.py &
python /sync-emi-gpu-test3/python/script/sample_taxi.py &
python /sync-emi-gpu-test4/python/script/sample_taxi.py &
python /sync-emi-gpu-test5/python/script/sample_taxi.py &

**Here is the sample sample_taxi.py script (I could not upload my zip).**

from blazingsql import BlazingContext
from dask.distributed import Client

import sys

def main():
	global client
	client = Client('172.30.6.16:8786')
	global bc
	bc = BlazingContext(dask_client = client, network_interface = 'ens5', allocator='existing')
	
	bc.create_table('sample_taxi_old',['/sync-emi-gpu-test1/python/lastprocesseddata/sample_taxi.parquet'])
	
	bc.create_table('sample_taxi_new',['/sync-emi-gpu-test1/python/newdata/sample_taxi.parquet'])
	
	oldBlankRecordCheck=bc.sql('SELECT * FROM `sample_taxi_old` AS oldTable LIMIT 1').compute()
	newBlankRecordCheck=bc.sql('SELECT * FROM `sample_taxi_new` AS newTable LIMIT 1').compute()

	insertRecord=bc.sql('SELECT DISTINCT newTable.VendorID,newTable.tpep_pickup_datetime,newTable.tpep_dropoff_datetime,newTable.passenger_count,newTable.trip_distance,newTable.RatecodeID,newTable.store_and_fwd_flag,newTable.payment_type,newTable.fare_amount,newTable.extra,newTable.mta_tax,newTable.tip_amount,newTable.tolls_amount,newTable.improvement_surcharge,newTable.total_amount,newTable.pickup_x,newTable.pickup_y,newTable.dropoff_x,newTable.dropoff_y FROM `sample_taxi_new` AS newTable')
	insertCount=insertRecord.compute().count()
	if insertCount.max()>0: insertRecord.compute().to_parquet(f'/sync-emi-gpu-test1/python/inserts/sample_taxi.parquet')
	if insertCount.max()>0: insertRecord.compute().to_parquet(f'/sync-emi-gpu-test1/python/lastprocesseddata/sample_taxi_BlazingFullFile.parquet')

	deleteRecord=bc.sql('SELECT DISTINCT oldTable.VendorID, oldTable.tpep_pickup_datetime, oldTable.tpep_dropoff_datetime FROM `sample_taxi_old` AS oldTable')
	deleteCount=deleteRecord.compute().count()
	if deleteCount.max()>0: deleteRecord.compute().to_parquet(f'/sync-emi-gpu-test1/python/deletes/sample_taxi.parquet')
	
	bc.sql('SELECT DISTINCT  oldTable.VendorID,oldTable.tpep_pickup_datetime,oldTable.tpep_dropoff_datetime,oldTable.passenger_count,oldTable.trip_distance,oldTable.RatecodeID,oldTable.store_and_fwd_flag,oldTable.payment_type,oldTable.fare_amount,oldTable.extra,oldTable.mta_tax,oldTable.tip_amount,oldTable.tolls_amount,oldTable.improvement_surcharge,oldTable.total_amount,oldTable.pickup_x,oldTable.pickup_y,oldTable.dropoff_x,oldTable.dropoff_y FROM `sample_taxi_old` AS oldTable LEFT JOIN (SELECT DISTINCT VendorID,tpep_pickup_datetime,tpep_dropoff_datetime, 1 AS CommercientFlag FROM `sample_taxi_new`) AS newTable ON ( newTable.`VendorID` = oldTable.`VendorID` AND  newTable.`tpep_pickup_datetime` = oldTable.`tpep_pickup_datetime` AND  newTable.`tpep_dropoff_datetime` = oldTable.`tpep_dropoff_datetime`) WHERE newTable.CommercientFlag IS NULL  UNION ALL SELECT DISTINCT  VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,pickup_x,pickup_y,dropoff_x,dropoff_y FROM `sample_taxi_new`').compute().to_parquet(f'/sync-emi-gpu-test1/python/lastprocesseddata/sample_taxi_BlazingFullFile.parquet')

	insertRecord=bc.sql('SELECT DISTINCT  newTable.VendorID,newTable.tpep_pickup_datetime,newTable.tpep_dropoff_datetime,newTable.passenger_count,newTable.trip_distance,newTable.RatecodeID,newTable.store_and_fwd_flag,newTable.payment_type,newTable.fare_amount,newTable.extra,newTable.mta_tax,newTable.tip_amount,newTable.tolls_amount,newTable.improvement_surcharge,newTable.total_amount,newTable.pickup_x,newTable.pickup_y,newTable.dropoff_x,newTable.dropoff_y FROM `sample_taxi_new` AS newTable LEFT JOIN `sample_taxi_old` AS oldTable ON ( newTable.`VendorID` = oldTable.`VendorID` AND  newTable.`tpep_pickup_datetime` = oldTable.`tpep_pickup_datetime` AND  newTable.`tpep_dropoff_datetime` = oldTable.`tpep_dropoff_datetime` ) WHERE  oldTable.`VendorID` IS NULL AND oldTable.`tpep_pickup_datetime` IS NULL AND  oldTable.`tpep_dropoff_datetime` IS NULL ')
	insertCount=insertRecord.compute().count()
	if insertCount.max()>0: insertRecord.compute().to_parquet(f'/sync-emi-gpu-test1/python/inserts/sample_taxi.parquet')

	del insertRecord 

	del insertCount 

	deleteRecord=bc.sql('SELECT DISTINCT  oldTable.VendorID, oldTable.tpep_pickup_datetime, oldTable.tpep_dropoff_datetime FROM `sample_taxi_old` AS oldTable LEFT JOIN `sample_taxi_new` AS newTable ON ( newTable.`VendorID` = oldTable.`VendorID` AND  newTable.`tpep_pickup_datetime` = oldTable.`tpep_pickup_datetime` AND  newTable.`tpep_dropoff_datetime` = oldTable.`tpep_dropoff_datetime` ) WHERE  newTable.`VendorID` IS NULL AND  newTable.`tpep_pickup_datetime` IS NULL AND  newTable.`tpep_dropoff_datetime` IS NULL')
	deleteCount=deleteRecord.compute().count()
	if deleteCount.max()>0: deleteRecord.compute().to_parquet(f'/sync-emi-gpu-test1/python/deletes/sample_taxi.parquet')

	del deleteRecord 

	del deleteCount 

	dfNew=bc.sql('SELECT DISTINCT newTable.* FROM `sample_taxi_new` AS newTable INNER JOIN `sample_taxi_old` AS oldTable  ON (newTable.`VendorID` = oldTable.`VendorID` AND  newTable.`tpep_pickup_datetime` = oldTable.`tpep_pickup_datetime` AND  newTable.`tpep_dropoff_datetime` = oldTable.`tpep_dropoff_datetime`) ORDER BY  newTable.`VendorID`,  newTable.`tpep_pickup_datetime`,  newTable.`tpep_dropoff_datetime`') 

	dfOld=bc.sql('SELECT DISTINCT oldTable.* FROM `sample_taxi_new` AS newTable INNER JOIN `sample_taxi_old` AS oldTable  ON (newTable.`VendorID` = oldTable.`VendorID` AND  newTable.`tpep_pickup_datetime` = oldTable.`tpep_pickup_datetime` AND  newTable.`tpep_dropoff_datetime` = oldTable.`tpep_dropoff_datetime`) ORDER BY  oldTable.`VendorID`,  oldTable.`tpep_pickup_datetime`,  oldTable.`tpep_dropoff_datetime`') 

	updateRecord=bc.sql('SELECT DISTINCT  newTable.`VendorID`, newTable.`tpep_pickup_datetime`, newTable.`tpep_dropoff_datetime` FROM ( SELECT `sample_taxi_new`.* FROM `sample_taxi_new` LEFT JOIN `sample_taxi_old` ON `sample_taxi_new`.`VendorID` = `sample_taxi_old`.`VendorID` AND `sample_taxi_new`.`tpep_pickup_datetime` = `sample_taxi_old`.`tpep_pickup_datetime` AND `sample_taxi_new`.`tpep_dropoff_datetime` = `sample_taxi_old`.`tpep_dropoff_datetime` WHERE  `sample_taxi_old`.`VendorID` IS NOT NULL AND  `sample_taxi_old`.`tpep_pickup_datetime` IS NOT NULL AND  `sample_taxi_old`.`tpep_dropoff_datetime` IS NOT NULL) AS newTable LEFT JOIN (SELECT sample_taxi_new.`VendorID`,sample_taxi_new.`tpep_pickup_datetime`,sample_taxi_new.`tpep_dropoff_datetime` FROM `sample_taxi_new` INNER JOIN `sample_taxi_old` USING(VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,pickup_x,pickup_y,dropoff_x,dropoff_y)) AS oldTable ON (newTable.`VendorID` = oldTable.`VendorID` AND  newTable.`tpep_pickup_datetime` = oldTable.`tpep_pickup_datetime` AND  newTable.`tpep_dropoff_datetime` = oldTable.`tpep_dropoff_datetime`) WHERE  oldTable.`VendorID` IS NULL AND  oldTable.`tpep_pickup_datetime` IS NULL AND  oldTable.`tpep_dropoff_datetime` IS NULL')
	updateCount=updateRecord.compute().count()
	if updateCount.max()>0: updateRecord.compute().to_parquet(f'/sync-emi-gpu-test1/python/updates/sample_taxi.parquet')

	del updateRecord 

	del updateCount 

	bc.drop_table('sample_taxi_old')
	bc.drop_table('sample_taxi_new')

if __name__ == '__main__':
	main()
	del bc
	client.close()
	del client

sys.exit()

**Here is the command to create the Dask Scheduler and Worker. Run this before you run the python scripts.**
conda activate blazingnewversion
dask-scheduler &
dask-cuda-worker 172.30.6.16:8786 --rmm-managed-memory

**Expected behavior**
Complete on 1 or more GPUs without deadlocking.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)] AWS EC2 server

 - Method of BlazingSQL install: [conda, Docker, or from source] CONDA
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**----For BlazingSQL Developers----**
**Suspected source of the issue**
Where and what are potential sources of the issue

**Other design considerations**
What components of the engine could be affected by this?

**Comment by rommelDB** [comment]
Hi @chardog, thanks for reporting this issue.
Even though what you are trying to do is not officially supported nor heavily tested, we are currently investigating the source of such deadlocks.

I want to remark that using more than one context simultaneously may be a source of some issues due to the lack of resources unless some parameters are changed (e.g., pool size if applicable).

We would like to understand more about why it is necessary to run this type of simultaneous queries with this configuration (using one context for each script). Perhaps you could try test running several queries simultaneously but using only one shared context.

cc @williamBlazing @diegodfrf
