### ISSUE TITLE
[QST]Does one bsql cluster can only connect to one hdfs cluster

### ISSUE THREAD

**Issue by yangjiajun2014** [BlazingDB/blazingsql#1280]
Hello.According to the document,I see that we need a hadoop home which contains config files same as hadoop cluster.In our case,we need to connect multi hdfs clusters.How to do this?

**Comment by felipeblazing** [comment]
You can do the following:

```
bc.hdfs('data_1', 
        host='10.0.0.1', 
        port=5340, 
        user='ubuntu',
        kerb_ticket='/path/to/ticket')

bc.hdfs('data_2', 
        host='10.0.0.2', 
        port=5340, 
        user='ubuntu',
        kerb_ticket='/path/to/ticket')

bc.create_table('table_name1', 'hdfs://data_1/file.csv')
bc.create_table('table_name2', 'hdfs://data_2/file.csv')

**Comment by felipeblazing** [comment]
Is there something about this setup or the need for a single HADOOP_HOME that causes issues.

**Comment by williamBlazing** [comment]
Closing issue due to lack of information. @yangjiajun2014  please feel free to re-open the issue if you still need some help.
