### ISSUE TITLE
[FEA] Option to suppress print out in bc.s3

### ISSUE THREAD

**Issue by drabastomek** [BlazingDB/blazingsql#1288]
**Is your feature request related to a problem? Please describe.**
A call to `bc.s3(...)` to register an s3 bucket prints out a lot of unnecessary information back to the user. It's ok for a debugging etc but not needed in a day-to-day use.

**Describe the solution you'd like**
It would be great to have an option like `silent` or `verbose` to suppress the print out from calling `bs.s3(...)`. The only message back might be `print(f'Bucket {bucket} has been registered.')`.

**Describe alternatives you've considered**
Right now I suppress these by assigning the return to void

```python
_ = bc.s3('bsql', bucket_name='bsql')
```

**Comment by Christian8491** [comment]
@drabastomek , could you provide some env details? I just execute a basic `bc.s3() ` script using a nightly version and the only print out information that i saw was: `S3 Storage Plugin Registered Successfully`

**Comment by drabastomek** [comment]
Confirming -- on `rapids-nightly` it shows properly now. Closing.

![image](https://user-images.githubusercontent.com/3249948/107416373-409e0280-6ac9-11eb-8f76-ca25d0496545.png)
