### ISSUE TITLE
Memory Pools and Config Options memory[DOC]

### ISSUE THREAD

**Issue by chardog** [BlazingDB/blazingsql#1292]
When creating the BC (no DASK), I see the variables "initial_pool_size" and "maximum_pool_size " .  
How are these two variables affected if you set the config_options variables: BLAZING_PROCESSING_DEVICE_MEM_CONSUMPTION_THRESHOLD and BLAZING_DEVICE_MEM_CONSUMPTION_THRESHOLD ? 

See lines 1225-1295 in https://github.com/BlazingDB/blazingsql/blob/branch-0.18/pyblazing/pyblazing/apiv2/context.py#L1232

It is also unclear what will happen when other programs are running and competing for GPU memory. I think a bigger discussion page is needed on Pools (initial, and max sizes), and device memory (max, and the threshold), use of host memory (when, how, does it include swap file memory, max memory). In addition there is the rmm when using Dask, and how that comes into play.  I can tell this is quite a big discussion topic. If there are already topics out there perhaps we need a central document that hyperlinks to each of them.

**Comment by williamBlazing** [comment]
@chardog we are adding more documentation and explanation about how a lot of things work in the engine that will be added in this PR https://github.com/BlazingDB/blazingsql/pull/1434.

If you find that once this PR is merged and you look at the documentation you can generate and look at with it, if you find that some information is still missing, please feel free to reopen the issue and we can add more
