### ISSUE TITLE
Not able to install any packages in app.blazingsql.com

### ISSUE THREAD

**Issue by grananqvist** [BlazingDB/blazingsql#1302]
I am trying to use https://app.blazingsql.com/
There are many Python packages I am not able to install because I can't install any linux packages required:

```
apt-get download build-essential
dpkg -i --force-not-root --root=$HOME/.local $HOME/build-essential_12.4ubuntu1_amd64.deb
dpkg: error: unable to access dpkg status area: No such file or directory
```

This doesn't even work:
```
apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
```

**Comment by felipeblazing** [comment]
In the free version found on app.blazingsql.com you are not able to install anything. If you want to install your own packages consider signing up for the private beta.

**Comment by williamBlazing** [comment]
You can sign up for the private beta using this link:  https://forms.gle/TsPLuGUxz15hz98Q8

**Comment by grananqvist** [comment]
I see, thanks. This should probably be displayed somewhere.
