### ISSUE TITLE
[BUG] Blazing Hangs on Complex Case Conditions

### ISSUE THREAD

**Issue by mlahir1** [BlazingDB/blazingsql#1337]
The following Blazing Query Works Fine.
`bc.sql('''
SELECT col0, col1,
'abc' as ch
FROM table0
''')`

But when i add a complex Case statement to the same above logic, it hangs.

`
bc.sql('''
SELECT col0, col1,
CASE WHEN col2=1 OR coalesce(col3, col4) ='97' THEN 'gavsg' 
             WHEN col5 IN ('abcd', 'abc') THEN concat(col5, ' - ' , col5) 
             WHEN col6= 'PDC' AND col7 IN ('GF', 'GC', 'GY', 'GB') THEN 'GGGAE' 
             WHEN col6= 'PDC' AND col7 IN ('GM', 'GZ', 'GP') THEN 'GGGAS' WHEN col6 = 'GFD' THEN 'GFD - APPLY' 
             WHEN (col8 = 'Y' OR col9 IN (40, 42, 43, 45)) AND col7 IN ('SS', 'AP', 'WP', 'SP') THEN 'IDC-FLO-FDC-BDC-XDK' 
             WHEN (col8 = 'Y' OR col9 IN (40, 42, 43, 45)) AND col5 IN ('APPLY') THEN 'TOMMY-APPLY' 
             WHEN (col8 = 'Y' OR col9 IN (40, 42, 43, 45)) AND col5 IN ('LOLNY') THEN 'TOMMY-ASSM' 
             WHEN (col8 = 'Y' OR col9 IN (40, 42, 43, 45)) AND col5 IN ('X-DOCK') THEN 'TOMMY-XDK' 
             WHEN (col8 = 'Y' OR col9 IN (40, 42, 43, 45)) THEN 'IDC-FLO-BDC-XDK' 
             WHEN col6 = 'FDC' OR col7 IN ('SS', 'AP', 'WP', 'SP') THEN 'FDC-BDC-XDK' 
             WHEN col6 NOT IN ('BDC', 'GFD', 'PDC') THEN 'BDC-APPLY' 
             WHEN col6 = 'BDC' AND col5 IN ('APPLY') THEN 'BDC-APPLY' 
             WHEN col6 = 'BDC' AND col5 IN ('LOLNY', 'X-DOCK') THEN 'BDC-ASSM' 
             WHEN col6 = 'BDC' AND col5 IN ('ABC') THEN 'ABC' 
             WHEN col6 = 'BDC' AND col5 IN ('ABD') THEN 'ABD' 
             WHEN col6 = 'BDC' AND col9 = 37 THEN 'ABD' WHEN col6 = 'BDC' THEN 'BDC-ASSM' 
             ELSE '' END ghnk
FROM sco_item_dc_summ
''')
`

Blazing Version
`rapids-blazing            0.18.0a210107 
blazingsql                0.18.0a0 `

**Comment by Christian8491** [comment]
Hi @mlahir1 could you try the same query but replacing
`concat(col5, ' - ' , col5)`                        by 
` col5 || ' - ' || col5`
As BlazingSQL uses the ` || `operator to concatenate. If it still fails, please let us know.

**Comment by Christian8491** [comment]
FYI `concat` operator will be enabled from PR #1427

**Comment by williamBlazing** [comment]
@mlahir1 could you please check to see if this is still an issue?

**Comment by williamBlazing** [comment]
Reported as fixed

**Comment by mlahir1** [comment]
Its fixed in branch -0.19
