### ISSUE TITLE
[QST] Code hangs on bc = BlazingContext() command

### ISSUE THREAD

**Issue by niktasks** [BlazingDB/blazingsql#1342]
**What is your question?**
Hi, 
I have launched a BlazingSQL Container with Docker. In my Jupyter Lab i start my code as instructed in the documentation:

from blazingsql import BlazingContext

the code hangs on this part and I don't know why: 
bc = BlazingContext()

In all tutorials online this command takes maximum 2minutes. And when I execute one of the example Notebooks on the Blazingdb's platform it runs smoothly and very quickly as well. However, when I attempt to run the same example Notebook from my Jupyter Lab the code still hangs. Maximum time I've waited was 1 hour before I shut the Kernel down and restarted it, but with no luck. 

Does anyone have any suggestions?

**Comment by drabastomek** [comment]
Hi @niktasks -- what GPU do you have in your local machine?

**Comment by niktasks** [comment]
Hi @drabastomek I launched the container from a DGX A100 on a 40GB GPU.

**Comment by drabastomek** [comment]
Can you share the `docker run...` command you used to get the container? My understanding is that A100 require CUDA 11 on, both, host and docker.

**Comment by niktasks** [comment]
Docker run command:
nvidia-docker run --gpus all --rm -p 8888:8888 --name user1 \
  -v /mnt/dgxshare/nvidia_file:/blazingsql/notebooks/nvidia_file \
  blazingdb/blazingsql:latest
  
 Mounted folder : /mnt/dgxshare/nvidia_file

**Comment by drabastomek** [comment]
Thanks. Can you try 
```bash
docker pull rapidsai/rapidsai-nightly:0.18-cuda11.0-runtime-ubuntu18.04-py3.8

docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    -v /mnt/dgxshare/nvidia_file:/blazingsql/notebooks/nvidia_file \
    rapidsai/rapidsai-nightly:0.18-cuda11.0-runtime-ubuntu18.04-py3.8
```

Also, I noticed you are passing `--gpus all`. You might want to start the `BlazingContext` with Dask Client

```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
from blazingsql import BlazingContext

cluster = LocalCUDACluster()
client = Client(cluster)
print(client) ### use to monitor Dask Dashboard
bc = BlazingContext(dask_client=client)
```

I'd then suggest navigating to the Dask Dashboard to monitor what is going on on the box.

cc: @williamBlazing for his input just in case.

**Comment by niktasks** [comment]
Thank you for your help @drabastomek !! it worked immediately now! 
And the work got allocated pretty evenly with dask:
![image](https://user-images.githubusercontent.com/42255314/108414318-61362d00-722c-11eb-813c-c549b8731f0d.png)

**Comment by drabastomek** [comment]
WOOT!
