### ISSUE TITLE
[FEA] Allow users to specify file format type

### ISSUE THREAD

**Issue by randerzander** [BlazingDB/blazingsql#1352]
Sometimes workflows write files without a `.csv`, `.orc`, `.parquet` etc extension. In such cases, Blazing fails to read files in the directory.

It would be nice to allow the user to supply the format as an argument:
```
bc.create_table('table_name_02', 's3://dir_name/file2', format='parquet') 
```

**Comment by williamBlazing** [comment]
Hello @randerzander That argument exists:
https://docs.blazingdb.com/docs/create_table
The parameter is `file_format`, so you would do:
`bc.create_table('table_name_02', 's3://dir_name/file2', file_format='parquet') `

We are planning on making it a little more intuitive, in particular with regards to warnings and error messaging for when you need to provide that parameter, but it is there. 

I am going to close this issue for now. But if you think this feature can be improved, please feel free to re-open and add further comments. Thanks!
