### ISSUE TITLE
[QST] SQL Query Optimization before calling cuDF API 

### ISSUE THREAD

**Issue by RAbraham** [BlazingDB/blazingsql#1355]
Hi,
This may be not required but does BlazingSQL do any query optimization like conventional databases(theoretically, gaining performance) to the queries before talking to the cuDF API or is it a direct translation on to the cuDF API.

In other words, is the only difference between BlazingSQL and cuDF it's API? i.e. SQL vs Python?

Thanks,
Rajiv

**Comment by roaramburu** [comment]
Great question, BSQL creates a distributed execution graph with caching steps in between every kernel.

There is some plan optimization off the query, some predicate push down if there is Metadata on the file format (like apache parquet), and finally some physical plan optimization that happens before and during runtime that starts learning how big intermediate result sets are to make sure the query doesn't run out of memory.

Also while many kernels are cudf, many others are BSQL's own as well for more typical database operations (namely row wise operations).

**Comment by RAbraham** [comment]
Thank you very much!
