### ISSUE TITLE
[BUG] Column aliases are not being applied

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#1393]
**Describe the bug**
In the relational algebra plan generated by Calcite, in some cases, the aliases for columns are not being generated or propagated properly. 

**Steps/Code to reproduce bug**
The following query demonstrates the behavior:
```
select o1.o_orderkey as okey1, o2.o_orderkey as okey2 from orders as o1
                    inner join orders as o2 on o1.o_orderkey = o2.o_orderkey
                    and o1.o_orderkey < 10000
```
Its relational algebra is:
```
LogicalJoin(condition=[=($0, $1)], joinType=[inner])
  BindableTableScan(table=[[main, orders]], filters=[[<($0, 10000)]], projects=[[0]], aliases=[[o_orderkey]])
  BindableTableScan(table=[[main, orders]], projects=[[0]], aliases=[[o_orderkey]])
```

**Expected behavior**
As you can see in the example above, the aliases pushed down to the BindableTableScan are not the aliases provided but are instead the original column names

**----For BlazingSQL Developers----**
**Suspected source of the issue**
This will likely need to be addressed by the Calcite rules

**Comment by rommelDB** [comment]
Oh, I see, this is probably a side effect of removing the ProjectRemoveRule https://github.com/BlazingDB/blazingsql/pull/1379 cc @Christian8491

**Comment by rommelDB** [comment]
Clearly the E2E tests that verify the column names are incomplete, we should add more scenarios.

**Comment by Christian8491** [comment]
This issue is not caused due to removing the `ProjectRemoveRule` cc @rommelDB. However, when using just these rules in this order: 
```
FilterJoinRule.JoinConditionPushRule.JOIN, 
ProjectJoinTransposeRule.INSTANCE 
```
The aliases disapear. The logical plan we will get is:
```
LogicalJoin(condition=[=($0, $1)], joinType=[inner])
  LogicalProject(o_orderkey=[$0])
    LogicalFilter(condition=[<($0, 10000)])
      LogicalTableScan(table=[[main, orders]])
  LogicalProject(o_orderkey=[$0])
    LogicalTableScan(table=[[main, orders]])
```
But using the same rules, now in this order
```
ProjectJoinTransposeRule.INSTANCE 
FilterJoinRule.JoinConditionPushRule.JOIN
```
we will get 
```
LogicalProject(okey1=[$0], okey2=[$2])
  LogicalJoin(condition=[=($0, $2)], joinType=[inner])
    LogicalFilter(condition=[$1])
      LogicalProject(o_orderkey=[$0], <=[<($0, 10000)])
        LogicalTableScan(table=[[main, orders]])
    LogicalProject(o_orderkey=[$0])
      LogicalTableScan(table=[[main, orders]])
```

**Comment by rommelDB** [comment]
@Christian8491 is right, we have just verified that this 'lost aliases' issue was not considered, it comes from much earlier.
