### ISSUE TITLE
Implement a prototype to a create table from other RDBMS

### ISSUE THREAD

**Issue by aucahuasi** [BlazingDB/blazingsql#1395]
**Proposal 1**
Direct approach using only create table semantic:
```python
bc.create_table("dept_emp", "mysql://lucho:admin@localhost:3306/sampledb/dept_emp")
bc.create_table("titles", "postgres://luis:12345@localhost:3306/testdb/subchema/titles")
```

**Proposal 2**
2 step approach, similar to what we have with storage registration:
```python
bc.mysql("mysqldb1", "mysql://lucho:admin@localhost:3306/sampledb")
bc.create_table("dept_emp", "mysqldb1/dept_emp")

bc.postgres("pgdb1", "postgres://luis:12345@localhost:3306/testdb")
bc.create_table("titles", "pgdb1/subchema/titles")
```

cc @williamBlazing @felipeblazing @rommelDB

**Comment by aucahuasi** [comment]
@drabastomek @roaramburu feel free to make any suggestions here

**Comment by williamBlazing** [comment]
I think I like your Proposal 1 better.
The storage registration wants to act more like something that has a path. While for creating a table from other databases, there it can depend a lot on that database's APIs. In the case above, the communication with mysql or postgres looks like a path, but for other databases it might be more like:
`bc.create_table('table_name',from_database='google_big_query', schema=...,database=...,table=...,credentials=...)`

**Comment by roaramburu** [comment]
I agree with William's comments. Proposal 1 makes more sense to me, I can understand there being more complex fields to fill out in creating these tables off of databases and therefore more arguments might be necessary.

Love it though!

**Comment by aucahuasi** [comment]
@williamBlazing @roaramburu  thank you!
Yes if other RDBMS needs additional attributes to define the connection then we can ask for this arguments in the create_table method.
Maybe instead to ask a connection string for mysql/postgress we want to start asking the arguments for these too, so any registration will have the same semantics

**Comment by aucahuasi** [comment]
Also, another idea, if the users want to filter and select specific columns we may offer the argument `columns = ["col1", "col2"]`

**Comment by drabastomek** [comment]
I do like the proposal 1 as well. My only worry is with 'free flow' text for passwords but RDBMS were never good with that...

**Comment by aucahuasi** [comment]
thanks @drabastomek agree, but for that kind of API the user relies on environment variables or other mechanism and from those they load the password inside the python variable to be used as argument for the create table.
Of course we should never print or keep the sensible data, we're already managing quite well the password and sensible data for the storage API (bs.s3, bs.gcs, etc), so we will make sure to apply those same standards here.

**Comment by aucahuasi** [comment]
@felipeblazing I did a review about the internal APIs we have, I was thinking on start implementing these new components:
```shell
data_provider/SQLDataProvider.h
data_parser/SQLParser.h
```
Also the `SQLDataProvider` will need to use some external component called `RDMSInterface`. This new component will create/handle the SQL sessions for other RDBMSs (Note that this component is like our `FileSystemInterface` except that it will expose API for SQL databases). Additional, using this new interface we'll be able to support many backends (mysl, postgress, etc) and the higher level components (such like `SQLDataProvider`) will only need to know about `RDMSInterface`.

cc @williamBlazing @rommelDB @gcca  @Christian8491

**Comment by roaramburu** [comment]
Might be an orthogonal topic, but does this take into account the ability to do predicate pushdown to the DBMS one has created a table off of?

**Comment by aucahuasi** [comment]
@roaramburu Was thinking the same yesterday, not only that, in the future we can offer a way to:
- select which columns
- predicated push down / pre filters
- alias for the selected columns
- etc
The sky is the limit, I think once we have the basic feature in place we can make arranges to implement all of these enhancements.

**Comment by aucahuasi** [comment]
**Status**
This feature:
- Will be optional at build time (to make easy build for many platforms: powerpc, etc)
- Integrates directly into the ral physical plan thanks to the data_provider & data_parser API
- Allows to apply pre filtering (with the table filter arg)
- Allows to control the fetching process (with the batch size arg)
- Uses the projection cols based on the query and makes possible to apply predicate push down
- Support most of the MySQL types: string, enum, datetimes, numeric, etc (this was based on the cudf support)
- Support importing nulls into cudf columns
- There are some progress with SQLite and PostgreSQL but the goal is to focus on MySQL for a first release!
- // TODO end to end tests

```python
## API:
from blazingsql import BlazingContext
​
bc = BlazingContext()
bc.create_table("filtered_depts", "departments",
                from_sql = "mysql",
                sql_hostname = "localhost",
                sql_port = 3306,
                sql_username = "lucho",
                sql_password = "admin",
                sql_schema = "employees",
                sql_table_filter = "dept_name LIKE '%a%'",
                sql_table_batch_size = 100)
query = """select dept_name from filtered_depts"""
df = bc.sql(query)
print(df)
```

​Output:
```shell​
BlazingContext ready
            dept_name
0             Finance
1     Human Resources
2           Marketing
3  Quality Management
4            Research
5               Sales
```

**Comment by aucahuasi** [comment]
@roaramburu @drabastomek This is another proposal for the API, please let me know what do you think

```python
from blazingsql import BlazingContext
​
bc = BlazingContext()

# shared connection
# - we create a shared connection so the user can reuse it many times
# - the 'schema' arg is optional, the user may set any schema later (see create_table for table2)
mysql_conn = bc.mysql(hostname = "localhost",
                      port = 3306,
                      username = "lucho",
                      password = "admin",
                      schema = "employees")

# we pass to the create table the shared connection
bc.create_table("filtered_depts", "departments",
                from_sql = mysql_conn,
                sql_table_filter = "dept_name LIKE '%a%'",
                sql_table_batch_size = 100)

query = """select dept_name from filtered_depts"""
df = bc.sql(query)
print(df)

bc.create_table("table2", "sales",
                from_sql = mysql_conn,
                sql_schema = "salesdb" # note we can use other schema too
                sql_table_filter = "id < 2000",
                sql_table_batch_size = 5000)

query = """select * from table2"""
df = bc.sql(query)
print(df)
```

**Comment by roaramburu** [comment]
Yeah, we want to take off `sql_` in front o fall the arguments, it doesn't seem to add anything for the user.

I also want to remove `table_filter` that should be figured out through the SQL query, not through a python argument.

`batch_size` should be an optional argument (if it is not) and it should default to something we think is a good idea for now.

i prefer everything to be in `.create_table()` and not in a new argument called `.mysql()`.

**Comment by aucahuasi** [comment]
Great, regarding the _table_filter_ I can remove it, you're right. I think is better to let the engine figure out how to apply that filter to the sql provider.

Currently the engine doesn't support computing those predicates at the level of the sql provider. All the fetching process happens in the sql provider and for now we support only to set which columns we want to fetch (the projections), but not what predicates to apply for the provider.

I can implement that in the future, so the engine have full support of this feature. btw I just created a new issue here https://github.com/BlazingDB/blazingsql/issues/1417 cc @felipeblazing @williamBlazing 

Thanks for your feedback @roaramburu

**Comment by aucahuasi** [comment]
@roaramburu If we don't process the filter at the moment we create the table, the engine will need to make sure the sql expression is compatible with the sql dialect of the sql database. This last part, implies the engine must implement the sql parsers for each sql dialect (to parse the filter predicates with different styles of operators, naming conventions, etc)

Perhaps, it would be good to leave that argument for now (since it is already working) although I agree we need to make the engine use the filter at the moment of running the query instead cc @felipeblazing @williamBlazing
