### ISSUE TITLE
[BUG] E2E test groupBy 07 fails with nulls

### ISSUE THREAD

**Issue by rommelDB** [BlazingDB/blazingsql#1402]
query = "SELECT count(distinct l_orderkey),
                        count(distinct l_partkey),
                        count(distinct l_suppkey)
                    FROM lineitem
                    GROUP BY l_orderkey, l_partkey, l_suppkey"

```
ERROR:
Different number of rows blzSQLresult: 470378 PyDrill result: 585852

FAILED TESTS
========================================================
  TestGroup InputType Result   TestId
0  Group by       gdf   Fail  TEST_07
1  Group by       orc   Fail  TEST_07
2  Group by   parquet   Fail  TEST_07
3  Group by       psv   Fail  TEST_07
```

**Comment by kharoc** [comment]
Different number of rows blzSQLresult: 470378 PyDrill result: 585852

Different number of rows blzSQLresult: 470378 PySpark result: 585852
