### ISSUE TITLE
Merge and deploy new Doxygen docs

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#1435]
- We need to merge in the branch that has all the new Doxygen docs
- Need to create script that can publish docs to github pages
- Need to automate process of publishing. This would trigger whenever we have a new release (merging branch-0.XX to main). Automating this is optional, only if its easy and not based on gpuCI
- Add process to Release SOP (William)

**Comment by drabastomek** [comment]
Outlining the build process so we do not check in unnecessary files:

1. The documentation SPHIX source code lives inside `docsrc` folder. This folder shall only contain source files necessary for *building* the docs (RST of static files, configuration, etc.) It shall **NOT** contain any of the RST files generated by Doxygen from the C++ side: these will be generated automatically when the GitHub actions run.
2. Upon successful merge of feature-branch to the `main` branch, the GitHub actions shall run `make` inside `docsrc` and build all the files to serve the documentation: the `breathe` and `exhale` will then run Doxygen and build the API docs pages for the C++ side, and the rest of the Sphinx process will scrape the Python scripts for all the docstrings and create the final HTML view of the documentation.
3. Once the HTML documentation is built, the `build` folder will be moved/overwrite the `docs` folder in the root of the repo where Github pages will serve it.

**Comment by felipeblazing** [comment]
rerun tests
