### ISSUE TITLE
Function - calculate memory impact

### ISSUE THREAD

**Issue by SinsBre** [BlazingDB/blazingsql#145]
**Is your feature request related to a problem? Please describe.**

There is difficult to know if a file will fit in memory when importing to blazingsql.

**Describe the solution you'd like**
I would like either:

A)
`bc.estimate_mem_usage(csv/parquet/gdf/pdf):
    <do calculations>
    return value_mem_usage
`

B)
`bc.fits_in_mem(csv/parquet/gdf/pdf):
    available_mem = get available gpu-memory
    value_mem_usage = <calculate file impact>
   if available_mem - value_mem_usage > 0:
        return True
   else:
        return False
`

**Comment by williamBlazing** [comment]
@SinsBre  The engine currently now executes queries in a batching fashion, so it should not run out of memory. It also dynamically adapts to the data as it is executing, which makes it challenging to pre-emptively know how much data it will require to process. We will be closing this issue for now. If you have used the latest version of the engine and you still feel that this should be a high priority feature, please re-open the issue and we can discuss it. Thanks.
