### ISSUE TITLE
[BUG] Window function throws stoi for ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING

### ISSUE THREAD

**Issue by drabastomek** [BlazingDB/blazingsql#1510]
**Describe the bug**
At the moment cannot use this window as it throws `stoi`

**Steps/Code to reproduce bug**
```python
import cudf
import blazingsql as bsql

bc = bsql.BlazingContext()

aaa = cudf.DataFrame({
'A': [1,1,1,2,2,3,4,5,5]
, 'B': [1,7,9,4,5,6,1,3,3]
, 'C': [3,4,10,3,4,12,3,4,11]
})
bc.create_table('aaa', aaa)

bc.sql('''
SELECT A
, B
, C
, AVG(C) OVER (PARTITION BY A ORDER BY B ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING)
FROM aaa
''')
```

**Expected behavior**
An moving average is calculated

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of BlazingSQL install: from source
 - **BlazingSQL Version**: ba4a97a3ce3f1c733a135bf88518f2f67b12b519

**Comment by williamBlazing** [comment]
this has been resolved
