### ISSUE TITLE
[BUG] S3 File Not Found

### ISSUE THREAD

**Issue by RXY3832** [BlazingDB/blazingsql#184]
BlazeSQL is unable to find s3 files that are (and have been confirmed) to actually be in S3.

`ParseSchemaError``                          Traceback (most recent call last)
ParseSchemaError: [ParseSchema Error] Path '/test/rocky2/restid=000002/' does not exist. File or directory paths are expected to be in one of the following formats: For local file paths: '/folder0/folder1/fileName.extension'    For local file paths with wildcard: '/folder0/folder1/*fileName*.*'    For local directory paths: '/folder0/folder1/'    For s3 file paths: 's3://registeredFileSystemName/folder0/folder1/fileName.extension'    For s3 file paths with wildcard: '/folder0/folder1/*fileName*.*'    For s3 directory paths: 's3://registeredFileSystemName/folder0/folder1/'    For gs file paths: 'gs://registeredFileSystemName/folder0/folder1/fileName.extension'    For gs file paths with wildcard: '/folder0/folder1/*fileName*.*'    For gs directory paths: 'gs://registeredFileSystemName/folder0/folder1/'    For HDFS file paths: 'hdfs://registeredFileSystemName/folder0/folder1/fileName.extension'    For HDFS file paths with wildcard: '/folder0/folder1/*fileName*.*'    For HDFS directory paths: 'hdfs://registeredFileSystemName/folder0/folder1/'
Exception ignored in: 'cio.parseSchemaPython'
cio.ParseSchemaError: [ParseSchema Error] Path '/test/rocky2/restid=000002/' does not exist. File or directory paths are expected to be in one of the following formats: For local file paths: '/folder0/folder1/fileName.extension'    For local file paths with wildcard: '/folder0/folder1/*fileName*.*'    For local directory paths: '/folder0/folder1/'    For s3 file paths: 's3://registeredFileSystemName/folder0/folder1/fileName.extension'    For s3 file paths with wildcard: '/folder0/folder1/*fileName*.*'    For s3 directory paths: 's3://registeredFileSystemName/folder0/folder1/'    For gs file paths: 'gs://registeredFileSystemName/folder0/folder1/fileName.extension'    For gs file paths with wildcard: '/folder0/folder1/*fileName*.*'    For gs directory paths: 'gs://registeredFileSystemName/folder0/folder1/'    For HDFS file paths: 'hdfs://registeredFileSystemName/folder0/folder1/fileName.extension'    For HDFS file paths with wildcard: '/folder0/folder1/*fileName*.*'    For HDFS directory paths: 'hdfs://registeredFileSystemName/folder0/folder1/'`
`

I start the BlazingContext and  set the s3 details like so:

``
s3_bc = BlazingContext()

s3_bc.s3('tld', 
      bucket_name=NAME, 
      access_key_id=auth_config["s3_access_key_id"], 
      secrect_key=auth_config["s3_secret_access_key"])

s3_bc.create_table('tld_s3', '/test/rocky2/restid=000002/')
``

I tried it several ways, all with the same error.

I tried giving it the file name as: 
1. '/test/rocky2/restid=000002/'
2. '/test/rocky2/restid=000002/*_part_*.*'
3.  '/test/rocky2/restid=000002/*_part_*.parquet'
4. '/test/rocky2/restid=*/*_part_*.parquet'
5. '/test/rocky2/*/*_part_*.parquet'
6. '/test/rocky2/*/*'
7. And as a list of files with full path (which included s://BUCKET_NAME).

I have confirmed the files are in s3.

**Comment by RXY3832** [comment]
Searched the web, found little in the way of useful examples of how to use S3 with BlazingSQL. In the docs, the examples are bare and when followed, lead to an error that is not factual. 

As the above states, the function to create tables from S3 says the files are not there. The files are very much there and the credentials are correct. This was checked multiple times.

As of know, the S3 function **does not work**. Please advice on when you'll be able to fix it. We may need to move on and not include BlazingSQL in our current project if the S3 function is not fixed shorty.

**Comment by williamBlazing** [comment]
When using S3, file names need to be refered to as:
`s3://test/rocky2/restid=000002/part.parquet`

meaning it should start with `s3://`

**Comment by gumdropsteve** [comment]
> When using S3, file names need to be refered to as:
> `s3://test/rocky2/restid=000002/part.parquet`
> 
> meaning it should start with `s3://`

@RXY3832 here's some examples [registering S3 & creating multiple tables](https://twitter.com/blazingsql/status/1214651455681904640?s=20) & [registering S3, creating & querying a table](https://twitter.com/blazingsql/status/1214705495279169536?s=20) that display the starting with `s3://` format & should be helpful.
