### ISSUE TITLE
[BUG] Hive querying returns "hdfs path not found" error

### ISSUE THREAD

**Issue by jcuda000001** [BlazingDB/blazingsql#186]
**Describe the bug**
I'm trying the new Hive querying feature (in v11) using pyhive. Pyhive connection and cursor are created correctly. When I call the create_table() operation, the command fails with hdfs path not found. The error message shows that the hdfs path is collected correctly, so the pyhive connection 
 and the metadata collection in get_hive_table() may be working correctly.
Error snippet: "ParseSchemaError: [ParseSchema Error] Path 'hdfs://.../../../' does not exist."

**Steps/Code to reproduce bug**
from blazingsql import BlazingContext
from pyhive import hive
bc = BlazingContext()
cursor = hive.connect('your_hive_ip_address').cursor()
bc.create_table("hive_db_name.hive_table_name",cursor) # fails here

**Expected behavior**
bc.create_table() should succeed

**Additional context**
Not HDFS register step followed while testing pyhive based connection.

**Comment by jcuda000001** [comment]
Even the HDFS approach mentioned in the following doc also throws the same error
https://docs.blazingdb.com/docs/hdfs

**Comment by jcuda000001** [comment]
Issue #184 seems to be related as well.

**Comment by felipeblazing** [comment]
You didnt register the hdfs file system.

**Comment by jcuda000001** [comment]
@felipeblazing  I did register hdfs file system

**Comment by haragr** [comment]
> Even the HDFS approach mentioned in the following doc also throws the same error
> https://docs.blazingdb.com/docs/hdfs

Hi,
@jcuda000001  Were you able to solve this?
Thanks
