### ISSUE TITLE
[BUG] Demos on the website are using deprecated statements

### ISSUE THREAD

**Issue by rommelDB** [BlazingDB/blazingsql#249]
## Report incorrect documentation

**Location of incorrect documentation**
Script demos on https://blazingsql.com/

**Describe the problems or issues found in the documentation**
The function call .get() and the use of .columns to get a gdf are deprecated.

**Steps taken to verify documentation is incorrect**
Running those scripts on the last stable release throws error messages in the case of calling .get() and in the use of .columns we will get an undesired output. 

**Suggested fix for documentation**
Remove all occurrences of .get() and .columns.

**Comment by rommelDB** [comment]
FYI: @roaramburu @Kellynunez @aucahuasi

**Comment by gumdropsteve** [comment]
https://github.com/BlazingDB/bsql-demos/pull/16

**Comment by gumdropsteve** [comment]
https://github.com/BlazingDB/bsql-demos/pull/16 has been merged & Colab demos syntax updated.
