### ISSUE TITLE
[DOC] drop_table is not in the docs

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#272]
`bc.drop_table('table_name')` needs to be in the readme.io documentation

**Comment by gumdropsteve** [comment]
@williamBlazing how's this?

Single GPU: https://docs.blazingdb.com/docs/single-gpu#section-drop-a-table

Multiple GPUs: https://docs.blazingdb.com/docs/distributed#section-single-node-multiple-gpu-with-local-cuda-cluster

Using BSQL: https://docs.blazingdb.com/docs/using-blazingsql#section-drop-tables
