### ISSUE TITLE
[DOC] EXPLAIN FUNCTION

### ISSUE THREAD

**Issue by roaramburu** [BlazingDB/blazingsql#316]
## Report incorrect documentation
There is no documentation on `.explain()`.

**Comment by gumdropsteve** [comment]
Added `.explain()` to 
- 10 Minutes to BlazingSQL: https://docs.blazingdb.com/docs/using-blazingsql#section-explain
- Single GPU: https://docs.blazingdb.com/docs/single-gpu#section-explain
- Multiple GPUs: https://docs.blazingdb.com/docs/distributed
