### ISSUE TITLE
Single Column Results as Series 

### ISSUE THREAD

**Issue by gumdropsteve** [BlazingDB/blazingsql#335]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to extract the column from single column results.

**Describe the solution you'd like**
Results with just 1 column return as Series (cudf.core.series.Series).

**Describe alternatives you've considered**
Current working solution is;
```
query = 'SELECT column FROM table'
values = bc.sql(query)['column']
```
Which in practice looks something like;
![image](https://user-images.githubusercontent.com/43570913/73639011-5c520b80-4620-11ea-83da-c522ecfd577d.png)

**Additional context**

**----For BlazingSQL Developers----**
**How and where should this be implemented?**
What part of the code should be feature be implemented? 
- https://github.com/BlazingDB/blazingsql/blob/branch-0.12/pyblazing/pyblazing/apiv2/context.py#L751

Naive / simple fix;
```
        if self.dask_client is None:
            result = cio.runQueryCaller(
                        masterIndex,
                        self.nodes,
                        nodeTableList[0],
                        fileTypes,
                        ctxToken,
                        algebra,
                        accessToken)
        # is there only 1 column in the result
        if len(result.columns) == 1:
            # convert it to a series
            result = result[result.columns[0]]
```

**Other design considerations**
What components of the engine could be affected by this? 
- multi-column results 
- speed of results being returned  
- Dask results 
  - https://github.com/BlazingDB/blazingsql/blob/branch-0.12/pyblazing/pyblazing/apiv2/context.py#L683
  - https://github.com/BlazingDB/blazingsql/blob/branch-0.12/pyblazing/pyblazing/apiv2/context.py#L776

**Testing considerations?**
What sort of unit tests and/or End to End tests be implemented to test this?
- Make sure that this doesn't leak into multi-column results
- Test idea: Applied example where results being passed can not be a DataFrame;
```
# pull single column results
series_test_results = bc.sql('SELECT column FROM table')
# these should be a series 
if str(type(series_test_results)) != "<class 'cudf.core.series.Series'>":
    # these are not a series
    raise Exception('FAILED SERIES TYPE TEST')

# pull multi column results
series_test_results = bc.sql('SELECT column, column2 FROM table')
# these should be a dataframe 
if str(type(series_test_results)) != "<class 'cudf.core.dataframe.DataFrame'>":
    # these are not a dataframe
    raise Exception('FAILED DATAFRAME TYPE TEST')
```

**Comment by felipeblazing** [comment]
When considering good api design we want function return types to be consistent. A function that returns different types depending on the context is not consistent and in many cases makes it impredictable if the code generating the result has an indeterminate number of columns.  Series and DataFrame dont have exactcly matching apis so this could be a source of bugs. Now they have to add code to check if the result they have is a single column Series or a Dataframe. If you want to get the series the code you showed above would be the canonical way of doing that.
