### ISSUE TITLE
[BUG] - Java Runtime error

### ISSUE THREAD

**Issue by SinsBre** [BlazingDB/blazingsql#394]
**Describe the bug**
The script produces the expected result in csv.

Fatal error detected by the Java Runtime Environment after script finish.

Result is hs_err_pid*.log
Problematic frame:
 C  [device_buffer.cpython-37m-x86_64-linux-gnu.so+0x4fdd]  __pyx_tp_dealloc_3rmm_4_lib_13device_buffer_DeviceBuffer(_object*)+0x3d

or

 Problematic frame:
 C  [libblazingsql-engine.so+0x155514]  std::_Sp_counted_ptr_inplace<blazingdb::transport::Node, std::allocator<blazingdb::transport::Node>, (__gnu_cxx::_Lock_policy)2>::_M_get_deleter(std::type_info const&)+0x4

**Steps/Code to reproduce bug**
```
def data_prep(input, input_dtype, input_names):
    return cudf.read_csv(input, names=input_names, dtype=input_dtype, skiprows=1).drop_duplicates()

bc = BlazingContext()

gdf1 = data_prep(inp1, inp1_dt_arr, inp1_n_arr)
gdf2 = data_prep(inp2 ,inp2_dt_arr, inp2_n_arr)

bc.create_table('foo',gdf1)
bc.create_table('bar',gdf2)

res = bc.sql(query_stmt)
res.to_csv('foobar.csv')

//done
```

**Expected behavior**

The script should finish without java runtime error.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [conda]

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
     NAME="Ubuntu"
     VERSION="18.04.4 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.4 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux foobar-ubu 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Wed Feb 12 15:03:31 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  GeForce RTX 2080    Off  | 00000000:01:00.0  On |                  N/A |
     | 24%   30C    P8    12W / 215W |    684MiB /  7979MiB |     12%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      1671      G   /usr/lib/xorg/Xorg                            28MiB |
     |    0      1708      G   /usr/bin/gnome-shell                          57MiB |
     |    0      2897      G   /usr/lib/xorg/Xorg                           304MiB |
     |    0      3030      G   /usr/bin/gnome-shell                         199MiB |
     |    0      3798      G   /snap/pycharm-community/179/jbr/bin/java      40MiB |
     |    0      5216      G   ...quest-channel-token=7403487544388299686    51MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              8
     On-line CPU(s) list: 0-7
     Thread(s) per core:  1
     Core(s) per socket:  8
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               158
     Model name:          Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
     Stepping:            12
     CPU MHz:             2148.799
     CPU max MHz:         4900.0000
     CPU min MHz:         800.0000
     BogoMIPS:            7200.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            12288K
     NUMA node0 CPU(s):   0-7
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
     
     ***CMake***
     /usr/bin/cmake
     cmake version 3.10.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /home/foobar/anaconda3/envs/fresh_cs_bin_parser/bin/python
     Python 3.7.6
     
     ***Environment Variables***
     PATH                            : /home/foobar/anaconda3/envs/fresh_cs_bin_parser/bin:/home/foobar/anaconda3/condabin:/home/foobar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/foobar/anaconda3/envs/fresh_cs_bin_parser
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/foobar/anaconda3/condabin/conda
     # packages in environment at /home/foobar/anaconda3/envs/fresh_cs_bin_parser:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     blazingsql                0.12.0          cuda10.0_py37_6    blazingsql/label/cuda10.0
     bokeh                     1.4.0                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bsql-rapids-thirdparty    0.12.0                        0    blazingsql
     bsql-toolchain            0.12.0                        0    blazingsql
     bsql-toolchain-aws-cpp    0.12.0                        0    blazingsql
     bsql-toolchain-gcp-cpp    0.12.0                        0    blazingsql
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     certifi                   2019.11.28               py37_0    conda-forge
     cffi                      1.13.2           py37h8022711_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.2                      py_1    conda-forge
     cppzmq                    4.4.1                hc9558a2_0    conda-forge
     cryptography              2.8              py37h72c5cf5_1    conda-forge
     cudatoolkit               10.0.130                      0    nvidia
     cudf                      0.12.0                   py37_0    rapidsai
     cudnn                     7.6.0                cuda10.0_0    nvidia
     cupy                      7.1.1            py37he57b8b9_1    conda-forge
     curl                      7.68.0               hf8cf82a_0    conda-forge
     cyrus-sasl                2.1.27               he38ecfd_0    conda-forge
     cytoolz                   0.10.1           py37h516909a_0    conda-forge
     dask                      2.10.1                     py_0    conda-forge
     dask-core                 2.10.1                     py_0    conda-forge
     dask-cuda                 0.12.0                   py37_0    rapidsai
     dask-cudf                 0.12.0                   py37_0    rapidsai
     distributed               2.10.0                     py_0    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     fastavro                  0.22.9           py37h516909a_0    conda-forge
     fastrlock                 0.4             py37he1b5a44_1000    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fsspec                    0.6.2                      py_0    conda-forge
     future                    0.18.2                   py37_0    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     jinja2                    2.11.1                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     jpype1                    0.7              py37h9de70de_0    conda-forge
     krb5                      1.16.4               h173b8e3_0
     ld_impl_linux-64          2.33.1               h53a641e_7
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcudf                   0.12.0               cuda10.0_0    rapidsai
     libcurl                   7.68.0               hda55be3_0    conda-forge
     libedit                   3.1.20181209         hc058e9b_0
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1                hd88cf55_4
     libgcc-ng                 9.1.0                hdf63c60_0
     libgcrypt                 1.8.4             hf484d3e_1000    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
     libgpg-error              1.36                 he1b5a44_0    conda-forge
     libgsasl                  1.8.0             h19a2143_1004    conda-forge
     libhdfs3                  2.3               h311b756_1006    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libntlm                   1.4               h516909a_1002    conda-forge
     libnvstrings              0.12.0               cuda10.0_0    rapidsai
     libopenblas               0.3.7                h5ec1e0e_6    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.12.0               cuda10.0_0    rapidsai
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libxml2                   2.9.10               hee79883_0    conda-forge
     llvmlite                  0.31.0           py37h8b12597_0    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markupsafe                1.1.1            py37h516909a_0    conda-forge
     msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1                  he6710b0_1
     netifaces                 0.10.9          py37h516909a_1000    conda-forge
     numba                     0.48.0           py37hb3f55d8_0    conda-forge
     numpy                     1.18.1           py37h95a1406_0    conda-forge
     nvstrings                 0.12.0                   py37_0    rapidsai
     olefile                   0.46                       py_0    conda-forge
     openjdk                   8.0.192           h516909a_1004    conda-forge
     openssl                   1.1.1d               h516909a_0    conda-forge
     packaging                 20.1                       py_0    conda-forge
     pandas                    0.25.3           py37hb3f55d8_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pillow                    5.3.0           py37h00a061d_1000    conda-forge
     pip                       20.0.2                   py37_1
     psutil                    5.6.7            py37h516909a_0    conda-forge
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pyhive                    0.6.1                    py37_0
     pynvml                    8.0.4                      py_0    conda-forge
     pyopenssl                 19.1.0                   py37_0    conda-forge
     pyparsing                 2.4.6                      py_0    conda-forge
     pysocks                   1.7.1                    py37_0    conda-forge
     python                    3.7.6                h0371630_2
     python-dateutil           2.8.1                      py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     pyyaml                    5.3              py37h516909a_0    conda-forge
     re2                       2020.01.01           he1b5a44_0    conda-forge
     readline                  7.0                  h7b6447c_5
     requests                  2.22.0                   py37_1    conda-forge
     rmm                       0.12.0                   py37_0    rapidsai
     sasl                      0.2.1           py37he1b5a44_1001    conda-forge
     setuptools                45.2.0                   py37_0
     six                       1.14.0                   py37_0    conda-forge
     snappy                    1.1.8                he1b5a44_1    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sqlalchemy                1.3.13           py37h516909a_0    conda-forge
     sqlite                    3.31.1               h7b6447c_0
     tblib                     1.6.0                      py_0    conda-forge
     thrift                    0.11.0          py37he1b5a44_1001    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     thrift_sasl               0.3.0           py37h516909a_1001    conda-forge
     tk                        8.6.8                hbc83047_0
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_3    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.25.7                   py37_0    conda-forge
     wheel                     0.34.2                   py37_0
     xz                        5.2.4                h14c3975_4
     yaml                      0.2.2                h516909a_1    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.3                h3b9ef0a_0    conda-forge
     
</pre></details>

**Additional context**

**----For BlazingSQL Developers----**
**Suspected source of the issue**
Where and what are potential sources of the issue

**Other design considerations**
What components of the engine could be affected by this?

**Comment by SinsBre** [comment]
No issues running in jupyter.
Issue appears when running a bsql in a script.

**Comment by SinsBre** [comment]
Issue seems to be related to "bc = BlazingContext()".

**Comment by williamBlazing** [comment]
It seems like there is an issue with resource de-allocation when the script ends. How resources are managed and deallocated is changing significantly for our next version 0.13 so this issue will likely disappear on it own very soon. In the mean time, I would suggest trying to put the `BlazingContext()` and your code in general inside a `main()` function, since that tends to help the python garbage collector be more organized upon cleaning up at the end of the script. So your script should look like so:
```
def data_prep(input, input_dtype, input_names):
    return cudf.read_csv(input, names=input_names, dtype=input_dtype, skiprows=1).drop_duplicates()

def main():
    bc = BlazingContext()

    gdf1 = data_prep(inp1, inp1_dt_arr, inp1_n_arr)
    gdf2 = data_prep(inp2 ,inp2_dt_arr, inp2_n_arr)

    bc.create_table('foo',gdf1)
    bc.create_table('bar',gdf2)

    res = bc.sql(query_stmt)
    res.to_csv('foobar.csv')

if __name__ == "__main__":
    main()
```
