### ISSUE TITLE
[BUG] Intermittent crashes on distributed mode even with e2e tests that pass OK

### ISSUE THREAD

**Issue by rommelDB** [BlazingDB/blazingsql#396]
**Describe the bug**
Some queries fail intermittently with different error messages. So far we have identified the following scenarios:
- When the argument pool=False is passed to the BlazingContext, queries #12 and #13 fail with the message below:
```
cio.RunQueryError: [RunQuery Error] CUDA error encountered at: /home/rommel/cudf/cpp/src/strings/copying/concatenate.cu:101: 11 cudaErrorInvalidValue invalid argument
```
- When a test ends unexpectedly or when the test is canceled by the user, the next execution whatever the test gives an error:
```
python3.7: /home/rommel/miniconda3/envs/cudf-sources-0211/blazingsql/comms/src/blazingdb/transport/Server.cc:161: void blazingdb::transport::experimental::{anonymous}::connectionHandler(blazingdb::transport::experimental::{anonymous}::ServerTCP*, void*, int): Assertion `ok_message == "OK"' failed.
Aborted (core dumped)
```

**Steps/Code to reproduce bug**
To reproduce the bug we need to run the distibuted e2e tests with pool=False and nRALs=2.

**Expected behavior**
All coalesce queries should be run successfully every time.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: from source, branch0.13 (commit hash 11a0e4)

**Environment details**
Please run and paste the output of the `print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**----For BlazingSQL Developers----**
**Suspected source of the issue**
Where and what are potential sources of the issue

**Other design considerations**
What components of the engine could be affected by this?

**Comment by aucahuasi** [comment]
Ping @williamBlazing @rommelDB 
Also track these:
https://github.com/rapidsai/cudf/pull/4138
cudf https://github.com/rapidsai/cudf/issues/4055

See: engine/CommonOperations.h ral::utilities::experimental::concatTables
