### ISSUE TITLE
[QST] - SQL Query engine implementation architecture

### ISSUE THREAD

**Issue by archenroot** [BlazingDB/blazingsql#398]
Hi guys,

I am thinking to implement something like blazinggraph based on cugraph rapids subproject to implement some query language for graphs (cypher, gremlin, graphql, sparql) and I would like to reuse your approach as in general it could follow same pardigm, do you have any schemas of your architecture (query parser, query convertor, query server, etc.) so I can understand the code base and eventually try to convert it for graph usage.

Any schema diagrams welcomed....

**Comment by williamBlazing** [comment]
@archenroot sorry for the late reply. 
We do not have any up to date architecture diagrams, and our architecture is currently being updated as well.
I think that for your purposes your starting point should be the query parser. We use Apache Calcite to parse queries into a logical relational algebra plan. We then modify that plan and execute it. So, if you want to do a query language for graphs, you probably first want to figure out what you want to use, or how you want to implement, your parser to translate the query into a relational algebra plan of some sort. I hope this helps.
