### ISSUE TITLE
[BUG] libjava.so issue while import blazinsql

### ISSUE THREAD

**Issue by raviy0807** [BlazingDB/blazingsql#425]
**Describe the bug**
"Error occurred during initialization of VM
Unable to load native library: /opt/conda/envs/rapids/libjava.so: cannot open shared object file: No such file or directory"

**Steps/Code to reproduce bug**
The bug occur whenever i tries to import blazinsql.

Example: import blazinsql

**Environment overview (please complete the following information)**
 - Environment location: docker with ubuntu 18.04, cuda 10 and cnn 7 and rapids

**Comment by raviy0807** [comment]
> **Describe the bug**
> "Error occurred during initialization of VM
> Unable to load native library: /opt/conda/envs/rapids/libjava.so: cannot open shared object file: No such file or directory"
> 
> **Steps/Code to reproduce bug**
> The bug occur whenever i tries to import blazinsql.
> 
> Example: import blazinsql
> 
> **Environment overview (please complete the following information)**
> 
> * Environment location: docker with ubuntu 18.04, cuda 10 and cnn 7 and rapids

@williamBlazing , gumdropsteve: any suggestion on this

**Comment by williamBlazing** [comment]
Hello @raviy0807 how did you install BlazingSQL?
- Docker container from https://hub.docker.com/r/blazingdb/blazingsql
- Conda install? (stable or nightly?)
- Build from source? (stable or nightly?)

Could you detail as much as possible your installation process?

Could you provide the output of `conda list` ?

**Comment by raviy0807** [comment]
I used conda install nightly version on ubuntu 18.04 image. But as a work around i was able to solve by setting java path from docker file. 
JAVA_HOME=/opt/conda/envs/rapids/jre/bin/
