### ISSUE TITLE
[DOC] BlazingContext memory docs

### ISSUE THREAD

**Issue by lmeyerov** [BlazingDB/blazingsql#426]
## Report incorrect documentation

**Location of incorrect documentation**

* Source code (for `help(bc.BlazingContext)`)
* https://docs.blazingdb.com/docs (no API section??)

**Describe the problems or issues found in the documentation**

When using cudf & bc together, unclear if/how the rapids memory manager gets shared and how to separately+jointly control. Does blazing get its own? What happens if you `cudf.set_allocator` and then `bc(pool=...)`, both to cudf and to bc? ... What is recommended?

Also, answering this question was a bit confusing. I expected a section of the `/docs` to be `Python API` and basically just list `BlazingContext`, `create_table`, `sql`, etc.

**Steps taken to verify documentation is incorrect**

Slack ;-) grazing on 2-20

**Suggested fix for documentation**

* Say what it does in main docs + in-code docs
* ... + best practice guidance
* Have a clear api section in `/docs`...

**Comment by gumdropsteve** [comment]
@lmeyerov API section: https://docs.blazingdb.com/docs/blazingcontext

**Comment by lmeyerov** [comment]
Thanks! Funny enough, was just reading through the source code here today.
