### ISSUE TITLE
[QST] What is the optimal size of data file (parquet file)?

### ISSUE THREAD

**Issue by raviy0807** [BlazingDB/blazingsql#450]
**What is your question?**

For huge data like 60GB, what will be best approach to create the parquet file?

Should be have multiple parquet file or single parquet file? If multiple, then what should be max parquet size to achieve best blazing performance.
In which scenario, blazingsql will provide best performance?

**Comment by williamBlazing** [comment]
The recommended size is 0.5Gb - 1Gb

**Comment by raviy0807** [comment]
Thanks @williamBlazing . Do you have some performance analysis for that?
