### ISSUE TITLE
FIgure out source of inconsistency

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#464]

**Comment by williamBlazing** [comment]
Inconsistencies in results have been observed with 2 RAL on csv, parquet and/or orc:
TPCH Queries  TEST_15 
with revenue (suplier_no, total_revenue) as 
                (
                    select
                        l_suppkey, sum(l_extendedprice * (1-l_discount))
                    from
                        lineitem
                    where
                        l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-04-01' 
                    group by
                        l_suppkey
                )
                select
                    s.s_suppkey, s.s_name, s.s_address, s.s_phone, re.total_revenue
                from 
                    supplier as s 
                INNER JOIN revenue as re on s.s_suppkey = re.suplier_no
                where
                    re.total_revenue = (select max(total_revenue) from revenue)
                order by
                    s.s_suppkey
Timestamp  TEST_02
select l_suppkey, l_shipdate from lineitem where l_shipdate < TIMESTAMP '1993-01-01 10:12:48' and l_suppkey < 100 order by l_orderkey

**Comment by felipeblazing** [comment]
@kharoc 
Change teh query to 

```
with revenue (suplier_no, total_revenue) as
(
select
l_suppkey, cast(sum(l_extendedprice * (1-l_discount)) as int)
from
lineitem
where
l_shipdate >= date '1996-01-01' and l_shipdate < date '1996-04-01'
group by
l_suppkey
)
select
s.s_suppkey, s.s_name, s.s_address, s.s_phone, re.total_revenue
from
supplier as s
INNER JOIN revenue as re on s.s_suppkey = re.suplier_no
where
re.total_revenue = cast((select max(total_revenue) from revenue) as int)
order by
s.s_suppkey

```
