### ISSUE TITLE
Logging time for Performance Testing

### ISSUE THREAD

**Issue by kharoc** [BlazingDB/blazingsql#481]
**Is your feature request related to a problem? Please describe.**
This issue is related to add 3 columnas total time, loading time and total engine time.

**Describe the solution you'd like**
Total time will be gotten using time library.
loading time and total engine time will be gotten from blazingsql logs.
 
**Describe alternatives you've considered**
We will be considering all E2E Test to log times.

**Additional context**
For specific cases we will put focus especially on times about tpcx-bb and tpch queries..

**----For BlazingSQL Developers----**
**How and where should this be implemented?**
This feature include:
Save times on the current google spreadsheet  for all End To End Tests.

**Comment by williamBlazing** [comment]
Regarding the times:
The total time should only capture the time taken to run the `bc.sql()` statement for the query

For the other times, they will need to be captured immediately after the queries are run. 

For times you will get from the log, please provide a snippet here about how you are capturing that as soon as you have that to make sure it looks good. THanks!

**Comment by kharoc** [comment]
start_time = time.time()
                result_gdf = bc.sql(query_blz)
                end_time = time.time()
                total_time = (end_time - start_time)*1000
                log_result = bc.log("""SELECT
                        MAX(end_time) as end_time, query_id, 
                        MAX(load_time) AS load_time, MAX(total_time) AS total_time 
                    FROM (
                        SELECT
                            query_id, node_id,
                            SUM(CASE WHEN info = 'evaluate_split_query load_data' THEN duration ELSE 0 END) AS load_time,
                            SUM(CASE WHEN info = 'Query Execution Done' THEN duration ELSE 0 END) AS total_time,
                            MAX(log_time) AS end_time
                        FROM
                            bsql_logs
                        WHERE
                            info = 'evaluate_split_query load_data'
                            OR info = 'Query Execution Done'
                        GROUP BY
                            node_id, query_id
                        )
                    GROUP BY
                        query_id
                    ORDER BY
                        end_time DESC limit 1""")
                load_time = log_result['load_time']
                engine_time = log_result['total_time']

This is the snipped that I will use to get times for performance testing.

**Comment by williamBlazing** [comment]
looks good!
