### ISSUE TITLE
ArrayCache

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#489]

**Comment by williamBlazing** [comment]
void arrayCache.put(index, BlazingTable)
BlazingTable = arrayCache.get(index)

**Comment by williamBlazing** [comment]
`put` should do a resize if it needs to.
if `get` is called with an index that does not exist, it should wait. Or if the cache object is not there, it should wait
ArrayCache should use a mutex to support muti-processing

**Comment by williamBlazing** [comment]
ArrayCache should not have push and pop. It should not behave as a queue

**Comment by aocsa** [comment]
implement ArrayCache using a diccionary
