### ISSUE TITLE
Add partition specification to create_table

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#534]
Proposal:

bc.create_table(‘table name’, cursor, schema_name, table_name, partitions= {}, filetype);

The partitions parameter contains the partition name and value that we are looking for in the key, value pairs.
 

Example: we have partition on `col1` and `col1` has values from 1 to 1000, and we are just interested in values 10 to 19.

Our create table would look something like this,

bc.create_table(‘table name’, cursor, schema_name, table_name, partitions= {col1:[I for I in range(10:20)] }, filetype);

 doing this we do not have scan the filenames for rest of the folders/partitions.

Taking this a step further, we can skip the whole concept of pyhive cursor by just doing a create table with `bc`, keberos auth using the below prototype.

bc.create_table(‘table name’, path=’path to baser folder dir’, partitions= {}, filetype);
 

Here the partitions parameter contains partition names and values as key, value pairs. But in this case we have to make sure they follow the exact same order and all the partitions are present in keys.
 

Example:

We have partitions on `col1` and `col1` has values from 1 to 1000, and we are just interested in values 10 to 19.

Also the table is partitioned on `col2` and we need all the values. And the partitions of hive are present in the same order.

 

Our create table would look something like this,

bc.create_table(‘table name’, path=’path to baser folder dir’, dict= {col1:[I for I in range(10:20)], col2:[]}, filetype);

**Comment by williamBlazing** [comment]
The API implemented has two variants. With and without a cursor and they are as follows:

When using a hive cursor:
`bc.create_table('ptransactions', cursor, file_format='parquet', hive_table_name='ptransactions', partitions = {'t_year':[2017, 2018], 't_company_id':[2, 4, 6], 'alpha': ['abc']})`
With this use case, you are still defining the table with a hive cursor, but you can specify partitions which effectively filter the partitions you really care about. This means that data that is not in these partitions will never be read or touched. When using a Hive cursor, the create_table process knows the full set of partitions that exist and therefore in the `partitions` parameter, you do not have to mention all partitioned columns. If a partitioned column is not included in the `partitions` parameter, then it will assume you want all the values of that column. The `partitions` parameter is expected to be a dictionary where the keys are the partition column names and the value are the set of partition values you want.

When you are not using a hive cursor:
```
location='hdfs://localhost:54310/user/hive/warehouse/ptransactions'
bc.create_table('ptransactions', location, file_format='parquet', partitions = {'t_year':[2017, 2018], 't_company_id':[2, 4, 6], 'alpha': ['abc','defghi']}, partitions_schema = [('t_year','int'),('t_company_id','int'),('alpha','str')])
```
With this use case you do not need to connect to Hive, but you can still query a table that has been partitioned the way that a Hive table is partitioned. You need to provide it a base folder and a set of partitions in the `partitions` parameter. The dictionary needs to include all columns by which the table has been partitioned and in the correct order. You also need to provide a `partitions_schema` parameter to define the name and data type of the columns by which you are partitioning.
The `partitions` parameter is expected to be a dictionary where the keys are the partition column names and the value are the set of partition values you want.
The `partitions_schema` parameter is expected to be in a list of tuples, where each tuple is the column name and the column type as a string.

**Comment by mlahir1** [comment]
Thanks @williamBlazing
