### ISSUE TITLE
[QST] Has anyone actually gotten the Getting Started Colab notebook to even work

### ISSUE THREAD

**Issue by QzSG** [BlazingDB/blazingsql#541]
Spent a whole day trying to get a BlazingContext working, but none of the notebooks are updated nor working, almost all of them are broken, or is this a dead project?

**Comment by roaramburu** [comment]
We're deprecating our colab examples and those links. 

We have to invest a lot of time to get it to work every few weeks. The links will be killed soon and point to a new project that will let you run all of the demo notebooks.
