### ISSUE TITLE
[BUG] AVG(int_dtype_col) returns all 1s

### ISSUE THREAD

**Issue by gumdropsteve** [BlazingDB/blazingsql#543]
**Describe the bug**
Calling `avg()` on a column of `int` dtype returns all 1s.

**Steps/Code to reproduce bug**
Run [this Notebook](https://gist.github.com/gumdropsteve/46b5d9a5975f0db00f0528ec90e60121) in BSQL / RAPIDS v0.13 environment.

**Expected behavior**
Return accurate values. 

**Environment overview (please complete the following information)**
 - Environment location: Cloud (AWS)
 - Method of cuDF install: conda

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit dda3ae7721a952c187d4ae465cac17d1445bf859 (HEAD -> master, origin/master, origin/HEAD)
     Author: Winston A Robson <warobson@gmail.com>
     Date:   Wed Apr 8 15:55:05 2020 +0000
     
     Update data_visualization.ipynb
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux ip-172-31-0-233 4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Apr 14 00:24:11 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 440.48.02    Driver Version: 440.48.02    CUDA Version: 10.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
     | N/A   46C    P0    28W /  70W |   2362MiB / 15109MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      1718      C   ...a-environments/rapids-stable/bin/python   439MiB |
     |    0      2022      C   ...a-environments/rapids-stable/bin/python   433MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              4
     On-line CPU(s) list: 0-3
     Thread(s) per core:  2
     Core(s) per socket:  2
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
     Stepping:            7
     CPU MHz:             3202.664
     BogoMIPS:            4999.99
     Hypervisor vendor:   KVM
     Virtualization type: full
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            36608K
     NUMA node0 CPU(s):   0-3
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni
     
     ***CMake***
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /usr/bin/python
     Python 2.7.17
     
     ***Environment Variables***
     PATH                            : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda-environments/rapids-stable
     PYTHON_PATH                     :
     
     conda not found
     ***pip packages***
     /usr/bin/pip
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
     asn1crypto (0.24.0)
     boto3 (1.12.18)
     botocore (1.15.18)
     certifi (2019.11.28)
     chardet (3.0.4)
     cryptography (2.1.4)
     docutils (0.15.2)
     enum34 (1.1.6)
     futures (3.3.0)
     idna (2.9)
     ipaddress (1.0.17)
     jmespath (0.9.5)
     kaggle (1.5.6)
     keyring (10.6.0)
     keyrings.alt (3.0)
     mysqlclient (1.3.10)
     nvidia-ml-py (375.53.1)
     pip (9.0.1)
     pycrypto (2.6.1)
     pygobject (3.26.1)
     python-dateutil (2.8.1)
     python-slugify (4.0.0)
     pyxdg (0.25)
     requests (2.23.0)
     s3fs (0.2.2)
     s3transfer (0.3.3)
     SecretStorage (2.3.1)
     setuptools (39.0.1)
     six (1.14.0)
     text-unidecode (1.3)
     tqdm (4.43.0)
     urllib3 (1.25.8)
     wheel (0.30.0)
     
</pre></details>

**Additional context**
Workaround: cast to float before calling `avg()`
- `select avg(cast(col_name as float)) as col_name2 from table_name`
- see `In [4]:` in [the Notebook](https://gist.github.com/gumdropsteve/46b5d9a5975f0db00f0528ec90e60121) for example

**----For BlazingSQL Developers----**
**Suspected source of the issue**
C++ float vs double?

**Comment by williamBlazing** [comment]
An AVG of an int will be an INT.
