### ISSUE TITLE
[DOC] invalid syntax list?

### ISSUE THREAD

**Issue by gumdropsteve** [BlazingDB/blazingsql#622]
## Report incorrect documentation

**Location of incorrect documentation**
N/a

**Describe the problems or issues found in the documentation**
Where can I find a list of column names / words that can't be used?

![Screenshot_20200507-165713_Chrome](https://user-images.githubusercontent.com/43570913/81355658-0445fd80-9084-11ea-99b0-36d20237d83f.jpg)

**Steps taken to verify documentation is incorrect**
Asked DevOps.

**Suggested fix for documentation**
Add a list of column names / words that can't be used to the docs.

**Comment by gumdropsteve** [comment]
https://github.com/apache/calcite/blob/master/core/src/main/codegen/templates/Parser.jj#L6724 via @aucahuasi

**Comment by roaramburu** [comment]
@gumdropsteve update the docs to link to Apache Calcite's list of reserved words.

**Comment by gumdropsteve** [comment]
https://docs.blazingdb.com/docs/reserved-words

Calcite sources: [docs](https://calcite.apache.org/docs/reference.html#keywords), [code (GitHub)](https://github.com/apache/calcite/blob/master/core/src/main/codegen/templates/Parser.jj#L6740)
