### ISSUE TITLE
Implement TIMESTAMPDIFF and TIMESTAMPADD

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#630]
This is the syntax expected by Calcite

{fn TIMESTAMPADD(timeUnit, count, datetime)} | Adds an interval of count timeUnits to a datetime

{fn TIMESTAMPDIFF(timeUnit, timestamp1, timestamp2)} | Subtracts timestamp1 from timestamp2 and returns the result in timeUnits

timeUnit is just a key set of possible keywords (SECOND, MINUTE, HOUR, DAY, MONTH, YEAR)

for TIMESTAMPADD:
- count should be an integer that is from a column or a literal
- datetime should be a timestamp type that is form a column or a literal

for TIMESTAMPDIFF:
- timestamp1 should be a timestamp type that is form a column or a literal
- timestamp2 should be a timestamp type that is form a column or a literal

NOTE: we may not be able to support operations on purely literals at this point

**Comment by williamBlazing** [comment]
Actually TIMESTAMPDIFF is already implemented

**Comment by rommelDB** [comment]
There is an issue with the following query: select l_shipdate, l_commitdate, timestampdiff(**MONTH**, l_commitdate, l_shipdate ) as diff from lineitem order by l_shipdate, l_commitdate limit 20

For the lineitem table, the Blazing output is:
0  1992-01-03   1992-02-02  1702967296
1  1992-01-03   1992-02-03  1616567296
2  1992-01-03   1992-02-18   320567296
...

The expected (Pyspark) output is:
0  1992-01-03   1992-02-02   0.0
1  1992-01-03   1992-02-03   1.0
2  1992-01-03   1992-02-18   1.0
...

Therefore, more tests should be added to also verify the correctness with the other time units.

**Comment by rommelDB** [comment]
Current status, apparently Calcite is confusing the time unit factor for years and months:

timestampdiff
===============================================
SECOND d1 - d2 / 1000        OK
MINUTE d1 - d2 / 60000       OK
HOUR   d1 - d2 / 3600000     OK
DAY    d1 - d2 / 86400000    OK
MONTH  d1 - d2 / 1	     FAIL
YEAR   d1 - d2 / 12          FAIL

timestampadd
===============================================
SECOND + FACTOR * 1000	   :INTERVAL SECOND	OK	
MINUTE + FACTOR * 60000    :INTERVAL MINUTE	OK
HOUR   + FACTOR * 3600000  :INTERVAL HOUR	OK
DAY    + FACTOR * 86400000 :INTERVAL DAY   	OK
MONTH  + FACTOR * 1	   :INTERVAL MONTH	FAIL
YEAR   + FACTOR * 12       :INTERVAL YEAR       FAIL
