### ISSUE TITLE
[BUG] Blazing Context throws Error "expected str, bytes or os.PathLike object, not NoneType"

### ISSUE THREAD

**Issue by mlahir1** [BlazingDB/blazingsql#645]
### Code:
`bc = BlazingContext(dask_client=Client("127.0.0.1:8786"))`

### Reproducer:
1. Create dask scheduler
2. Create dask worker using `dask-cuda-worker tcp://<schip>:8786`

### Exception
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 826, in __init__
    ralPort, ralIp, cwd = connection.result()
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py", line 216, in result
    raise exc.with_traceback(tb)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 55, in loads
    return pickle.loads(x)
  File "/conda/envs/rapids/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 48, in <module>
    'lib/blazingsql-algebra.jar'))
  File "/conda/envs/rapids/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by williamBlazing** [comment]
Lets test this when creating tables from cudf DataFrame AND dask cudf DataFrame

**Comment by mlahir1** [comment]
@williamBlazing blazing context is not created in the first place to create the table.

**Comment by felipeblazing** [comment]
We need to find some time to replicate this. It did not happen when we tried using dask-cuda-worker so we need to see if theres some difference in how we both launch these.

**Comment by mlahir1** [comment]
@felipeblazing this works fine on single node. I am able to rep this issue only on multi nodes, k8 cluster.

**Comment by williamBlazing** [comment]
to replicate on scheduler you run:
`/conda/envs/rapids/bin/dask-scheduler`
in all nodes you run.
`/conda/envs/rapids/bin/dask-cuda-worker tcp://<schi-ip>:8786 --memory-limit 0 --nthreads 1`

**Comment by Christian8491** [comment]
```
~$ conda list | grep dask
dask                      2.19.0                     py_0    conda-forge
dask-core                 2.19.0                     py_0    conda-forge
dask-cuda                 0.15.0a200621           py37_37    rapidsai-nightly
dask-cudf                 0.15.0a200621   py37_gac5409487_1500    rapidsai-nightly

cudatoolkit=10.0
```

**Comment by williamBlazing** [comment]
This issue goes away if the dask-cuda-worker is created in the conda environment

**Comment by igorbb** [comment]
I am running dask cuda workers using dask mpi . That is what available in the HPC cluster we are restricted to.
I am having this same error, do you happen to have any instructions on what is the right way to initialize the dask-cuda workers?
