### ISSUE TITLE
[BUG] HostCacheMachine does not implement CacheMachine

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingsql#651]
**Describe the bug**
The whole point of having the CacheMachine interface is to ensure that people are able to add common functionality like that of logging to CachceMachine and have that work for all machines. As it stands I will have to duplicate all code I wrote for HostCacheMachine if I wante to capture it int he logs. 

**Steps/Code to reproduce bug**
HostCacheMachine should be forced to follow the same interface

**Comment by williamBlazing** [comment]
There is HostCacheMachine any more
