### ISSUE TITLE
[BUG] Benchmark q 01: hangs

### ISSUE THREAD

**Issue by Christian8491** [BlazingDB/blazingsql#693]
**Describe the bug**
-- Some context:
Q01 have 2 SQL statements. There are 136 GPUs. 
For the first query, tables were created from parquet files.
All GPUs end with successful the first query. 

To the second query,  table was created from a dask_cudf DataFrame ( as result of the first `bc.sql()`)
Then Only 95 GPUs try the second SQL step. Finally  it hangs.

**Expected behavior**
All GPUs should continue working with the second SQL .

**Comment by kingice** [comment]
When would it be fixed? Thanks.

**Comment by Christian8491** [comment]
Hi @kingice this feature is already fixed!
