### ISSUE TITLE
Include activation event logs

### ISSUE THREAD

**Issue by rommelDB** [BlazingDB/blazingsql#695]
https://jamboard.google.com/d/1dXkTScbP_A71ZHI4RxfyQUVGWsPRI1IVqsRx1elJRSo/viewer?f=8

Un kernel esta activo cuando esta procesando chunks, inactivo cuando no
un cache no esta activo ni inactivo
los edges estan activos o inactivos
el edge in esta activo caundo se esta procesando algun addToCache
el edge de salida esta activo caundo alguien hace removefromcache
y se pueden llamar multiples a la vez.

**Comment by williamBlazing** [comment]
Logging structure changed. This issue no longer applies
