### ISSUE TITLE
TPCH test 3 was commented because gpu ci test were failing, we need to fix that query

### ISSUE THREAD

**Issue by aucahuasi** [BlazingDB/blazingsql#734]

**Comment by williamBlazing** [comment]
query = """ select 
                    l.l_orderkey, sum(l.l_extendedprice * (1 - l.l_discount)) as revenue, o.o_orderdate, o.o_shippriority	                    l.l_orderkey, sum(l.l_extendedprice * (1 - l.l_discount)) as revenue, o.o_orderdate, o.o_shippriority
                from 	                from 
                    orders as o	                    orders as o
                INNER JOIN lineitem as l ON l.l_orderkey = o.o_orderkey	                INNER JOIN lineitem as l ON l.l_orderkey = o.o_orderkey
                INNER JOIN customer as c ON c.c_custkey = o.o_custkey	                INNER JOIN customer as c ON c.c_custkey = o.o_custkey
                where	                where
                    c.c_mktsegment = 'BUILDING'	                    c.c_mktsegment = 'BUILDING'
                    and o.o_orderdate < date '1995-03-15' 	                    and o.o_orderdate < date '1995-03-15' 
                    and l.l_shipdate > date '1995-03-15'	                    and l.l_shipdate > date '1995-03-15'
                group by	                group by
                    l.l_orderkey, o.o_orderdate, o.o_shippriority	                    l.l_orderkey, o.o_orderdate, o.o_shippriority
                order by	                order by
                    revenue desc, o.o_orderdate"""	                    revenue desc, o.o_orderdate"""
