### ISSUE TITLE
update readme.io docs

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#752]
Need to make sure latest docs include:
blazingsql.__info__()
how to create tables for hive with and without cursor
what else?

**Comment by gumdropsteve** [comment]
New links...

https://docs.blazingdb.com/docs/blazingsql-version-info

https://docs.blazingdb.com/docs/minio

https://docs.blazingdb.com/docs/pandas-dataframe

https://docs.blazingdb.com/docs/reserved-words
