### ISSUE TITLE
TPCX-BB Q12 issue

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#762]

**Comment by williamBlazing** [comment]
[q12-jun2-error.tar.gz](https://github.com/BlazingDB/blazingsql/files/4748812/q12-jun2-error.tar.gz)

**Comment by Christian8491** [comment]
Just for let you know. This query at scale factor 10 K now pass.

**Comment by Christian8491** [comment]
Closing this issue as `Q12` was validated at sf `1K` and succeed at sf `10K`
