### ISSUE TITLE
[BUG]  Invalid, non-fixed-width type.

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#787]
Issue in LogicalProject:
In Projection kernel batch 0 for LogicalProject(colA=[$0], colB=[$1], colC=[$2], CAST=[CAST($1):VARCHAR NOT NULL], CAST4=[CAST($2):VARCHAR NOT NULL]). What: cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1591854101578/work/cpp/src/column/column_factories.cpp:119: Invalid, non-fixed-width type.****

**Comment by williamBlazing** [comment]
The issue is caused by doing:
CAST(-999 as VARCHAR)

**Comment by Christian8491** [comment]
I tried to reproduce this issue using: 
`query = """SELECT CAST(-999 as VARCHAR) from nation"""`
 and do not found issues.

**Comment by Christian8491** [comment]
Closing this issue as the issue disappeared.
