### ISSUE TITLE
Get ORC Metadata and use with skipdata processing

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#795]
We can get the metadata using this: 
https://github.com/apache/orc/blob/master/c%2B%2B/include/orc/Statistics.hh

**Comment by williamBlazing** [comment]
All of our readers implement the arrow::io::RandomAccessFile interface, so that S3, HDFS or local files all use the same file interface. For the ORC metadata, we will need to implement InputStream interface:
https://github.com/apache/orc/blob/master/c%2B%2B/include/orc/OrcFile.hh#L37
but we will want to base it on our arrow::io::RandomAccessFile interfaces. 
All of our FileSystems implement the function `openReadable` which returns a `RandomAccessFile`.
We similarly want to implement a new function `openOrcInputStream` which returns a `InputStream`.

That InputStream object would internally have a RandomAccessFile but have additional things which RandomAccessFile does not provide for us.

InputStream requires the following:
uint64_t getLength()
      we can implement simply with RandomAccessFile.GetSize()
uint64_t getNaturalReadSize()
      this can be hardcoded depending on the FileSystem being used
void read(void* buf, uint64_t length, uint64_t offset)
     this can be implemented with RandomAccessFile.ReadAt(int64_t position, int64_t nbytes, int64_t * bytes_read, void * buffer)
 std::string& getName()
     this can be a string that comes from the URI originally used when creating openOrcInputStream

**Comment by williamBlazing** [comment]
The InputStream object for the LocalFileSystem could just use ORCs :
ORC_UNIQUE_PTR<InputStream> readLocalFile(const std::string& path);
And for HDFS we may or may not want to use:
ORC_UNIQUE_PTR<InputStream> readHdfsFile(const std::string& path);
but probably not because we do weird things to our file paths.

**Comment by ayushdg** [comment]
@williamBlazing Will this enable predicate pushdown while reading orc files?

**Comment by williamBlazing** [comment]
@ayushdg We do predicate pushdown at two different levels for Apache Parquet. First we look at the parquet metadata and we can evaluate the predicate on the metadata to know what rowgroups and files we can completely skip. Then after we read any file, we apply any filters we can at that stage. This issue is about being able to do the same for Apache Orc files. We right now do not read not act upon Orc metadata, but we do still apply filters immediately after a file read.

**Comment by williamBlazing** [comment]
Since we are having issue linking with conda orc package and our engine, i am currently doing exploratory work using some stand alone utility code.


Latest findings:
ORC metadata is available at the whole column level, the stripe level and the row_index level. Within each stripe there can be multiple row_indexes which is a group of rows (all three files i have been looking at have row_index strides of 10K rows. i.e. each row index group is 10K rows). Which means we have metadata granularity for every 10K rows, BUT cudf only gives us APIs for reading individial stripes, unless we also try to use the APIs that let us specify the number of rows to read and also starting at which rows number to start reading.

The metadata tells us for numbers:
min, max, sum, num values and if there are nulls. 
For strings:
min, max, total length (total of all the strigns), num values and if there are nulls
NOTE: we will have to see if the min and max of strings follows the same lexicography as our inequality operators

For timestamp columns there is:
min, max, upperbound, lowerbound, num values and if there are nulls. upper bound and lower bound seem to be an timezone offset version  of min and max. 
Example:
```
Data type: Timestamp
Values: 10000
Has null: no
Minimum: 1992-02-06 18:00:00.0
LowerBound: 1992-02-06 18:00:00.0
Maximum: 1998-10-24 19:00:00.0
UpperBound: 1998-10-24 19:00:00.1
```

**Comment by williamBlazing** [comment]
The latest status on the implementation of this issue is that run time linking isn't working with ORC due to issues with protocol buffers
