### ISSUE TITLE
Fix python/cython code style so that pr-builder gpuCI passes

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#796]
We need to check our python style so that it passes these checks:

https://github.com/BlazingDB/blazingsql/blob/branch-0.15/ci/checks/style.sh

This is how we can use these linters:
https://github.com/rapidsai/cudf/blob/branch-0.15/CONTRIBUTING.md#code-formatting

**Comment by Christian8491** [comment]
This was already merged whit this PR https://github.com/BlazingDB/blazingsql/pull/829
