### ISSUE TITLE
Implement Batch Job Executor

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#807]
Original design concepts can be found here https://docs.google.com/document/d/1u-9mhYMvU6yPfymeBYtAYwDYicx2Mymx616cipZ5qiU/edit 

Restated and summarized here:

**Context and Problem:**
In our current architecture all kernels run simultaneously (recent changes have enabled running only a subset of those kernels at a time) and all kernels in the run function try to pull batches from a CacheMachine and then run operations on those batches. There is nothing stopping each kernel to try to pull data onto the GPU and execute work. This means that if you have a lot of kernels simultaneously doing work you can easily run out of memory. 
We currently only have two mechanisms for controlling memory consumption:
1. When we place data into a CacheMachine, that data will be left in GPU, placed in CPU or on Disk depending on resource consumption at that point in time.
2. There is a MemoryMonitor that every 50ms (configurable) it checks the amount of GPU memory being consumed and if its too high, it will try to move some CacheData from GPU to CPU

These two memory consumption control mechanisms help, control memory consumption, but because there is nothing controlling how much work the kernels can collectively do, or whether they should wait until there is more memory available, that means its not that hard for the engine to run out of memory.

**General proposed solution:**
Each kernel, rather than executing all work inside its `run()` function, the `run()` function would instead generate jobs that are sent to a central Job executor. The central job executor would then run up to N (configurable) jobs in parallel using a thread pool. The job executor would also be able to optimize the execution of the jobs depending on priority policies. Additionally, the ability to run jobs will depend on there being enough gpu memory. If there is low gpu memory available, it would run less simultaneous jobs, that way it wont run out of memory. 

**This main concept serves to solve several problems:**
1. Resource management. Having one central executor, allows to manage compute and memory resources, so that the system is not overwhelmed
2. Optimization: Having one central executor should allows for implementing optimization policies to be able to run the whole graph faster. Smart optimization policies should in theory queue the jobs such that it minimizes movement of data on and off the GPU and also minimize bottlenecks, or having certain kernels waiting too long for other dependent kernels to finish.
3. Parallelism: In out current architecture, each kernel can really only be running one batch at a time. In this executor paradigm, multiple jobs can be queued for one kernel and these can be run simultaneously. So, if one kernel is at one point the bottleneck, then it ban be accelerated by running multiple of its batches simultaneously.

**General concept requirements:**
In order for the above precepts to work we need the following requirements:
1. All work done by a GPU needs to be able to be placed in a *job* that can be executed by the job executor
2. The jobs should not reference data that is already residing in GPU. Jobs that are just waiting to be executed, should not need to take up space, therefore the data that will be operated on by a job should be similar to a CacheData object, where it can reside in GPU, CPU or disk.
3. All jobs need to be threadsafe. Meaning, if a job is dependent on the state of a kernel, that state needs to be maintained in a threadsafe way.
4. The output of a job needs to able to be placed in a CacheMachine into a certain ordered position. For example if there are multiple jobs relating to an ORDER BY kernel, and these jobs are executed in parallel,  the output of these will need to end up in the output CacheMachine in the correct order, regardless of the order in which the actual batches were completed.

**Comment by rommelDB** [comment]
We must also consider from the beginning of this new design to implement a mechanism that allows us to determine/visualize the performance improvement or harm of applying this concurrent approach versus the sequential execution. 

Furthermore, it would be very valuable for debugging purposes and optimization to measure the impact of adjusting the execution parameters (e.g., the number of threads on the thread pool, size thresholds, and so on). Maybe we can consider other metrics such as degree of concurrency or efficiency, in addition to only seeing the final execution time.

**Comment by williamBlazing** [comment]
> We must also consider from the beginning of this new design to implement a mechanism that allows us to determine/visualize the performance improvement or harm of applying this concurrent approach versus the sequential execution.
> 
> Furthermore, it would be very valuable for debugging purposes and optimization to measure the impact of adjusting the execution parameters (e.g., the number of threads on the thread pool, size thresholds, and so on). Maybe we can consider other metrics such as degree of concurrency or efficiency, in addition to only seeing the final execution time.

We should be able to use the visualization that @felipeblazing built a while back. The work done by the kernels should not change much from one implementation to the new one, but more it will be restructured and executed in a different order.

**Comment by williamBlazing** [comment]
Here are some proposed APIs to show how this could work:

```
class JobExecutor {
JobExecutor(int num_concurrent_threads, std::shared_ptr<device_memory_resource> mem_resource, priority_scheme priority_scheme_type)

// this function would run num_concurrent_threads threads, each running `batch_runner()`
void run();


// This is one way we could implement this. But a key feature is that if memory consumption is too high, then we dont launch new jobs until it goes down. 
// ALthough it should not be necessary, we may want to add something that makes sure there is always at least one job running.
// We could also have tiers of memory consumption that dictates how many jobs we concurrently have running.
void batch_runner() {

    while (!query_done) {
        if (mem_resource under threshold){
            queue_mutex.lock();
            BatchJob job = std::move(job_queue.top());
            job.queue.pop();
            queue_mutex.unlock();
            job.launch();
        } else {
            sleep(memory_monitor_period); // wait a bit to allow memory monitor to release some memory before trying again
        }
    }

}


// Adding a job would create the priority object, depending on the current priority policy and then create the Job object with that priority policy
void add_job(kenel * exec_kernel, std::vector<std::unique_ptr<CacheData>> job_data, batch_info batch_info_struct){

    // We can have different batch priority policies, which change depending on requirements such as concurrency, workload size or something else
    // In the beginning, having different priority policies would be very useful to experiment with ways of opimizing the execution of the graph.
    batch_priority priority_object;
    if (priority_scheme_type == priority_scheme::Branch_Order){
        priority_object = Branch_Order_Priority(batch_info_struct);
    } else if (priority_scheme_type == priority_scheme::Branch_Order){
        priority_object = Percent_Complete_Priority(batch_info_struct);
    }
    BatchJob job(exec_kernel, std::move(job_data), priority_object);
    job_queue.push(job);
}


private:
std::mutex queue_mutex;
std::priority_queue<BatchJob> job_queue
std::shared_ptr<device_memory_resource> mem_resource
int num_concurrent_threads
std::atomic<bool> query_done;
int memory_monitor_period;

}


class BatchJob {

BatchJob(kenel * exec_kernel, std::vector<std::unique_ptr<CacheData>> job_data, batch_priority priority_object, batch_info batch_info_struct)


bool operator<(const BatchJob & job) {
    return this->priority < job.priority;
}

void launch(){
    this->exec_kernel->run_batch(job_data, batch_info_struct);    
}


private:
    kenel * exec_kernel;
    std::vector<std::unique_ptr<CacheData>> job_data;
    batch_priority priority_object;
    batch_info batch_info_struct;

}

batch_priority  is an interface. Different implementations would capture different information available in batch_info and implement different less than operator.
This works very well with the priority_queue because it allows us to define in one class interface, different ways of optimizing the graph.
The std::priority_queue would sort the queue every time you insert a new element. 
You could have the batch_priority object have access to the graph and get info on the state of the graph. This way, every time a new job is added the order of the 
jobs to be executed could change dinamically as the graph evolves.


batch_info is a struct that can hold whatever information we would need to set the priority of the jobs.
I would also need to know what batch number it is, since that information is necessary for some kernels so that the output of a job is added to the right place index of the output cache. (for example order by)

```

**Comment by felipeblazing** [comment]
Could the job executor be a bit more ignorant of what the resources being managed are? So there are many different resources that are needed to complete jobs. An example is that sending a tcp message incurs overhead in system memory. 


Sending messaging in general consumes precious network capacity and the network topology of these systems is complicated. There are many network interfaces. Their distance to and from each gpu to each nic is varied. I am not saying we take all this into account right now but I definitely think that we need to have a way of abstracting away resources so that things can require different kinds of resources.

Similarly we have things like local file i/o, i/o to remote file systems. And GPU <==> CPU connections as fast as NVLINK and as slow as PCIE. I am not advocating for handling all of this now but I think we can start future proofing by doing things like:

1. Understand that each job consumes different kinds of resources
2. Know the high level resources that we have to manage (CPU Memory, GPU Memory, threads, gpu processing time, network i/o, file i/o)

The question that arises for me is do we use different JobExecutors or do  we manage all the different resources we have within one job executor?

Do we agree that these executors have to look at more than just memory?

**Comment by williamBlazing** [comment]
I do agree that these Executors have to look at more than just memory. How the executives prioritize jobs that have different types of resource requirements I think need to be on the priority objects and the priority information that they handle. 

I don't think that we want to have different jobs executives that operate on different types of resources. Since most jobs will have need of multiple different types of resources I think it is best to control them with a single job executor. 

In the `batch_runner()` function mentioned above, there is a an if statement that checks if there's enough memory available for the job. That same concept can be applied to other types of resources.

**Comment by williamBlazing** [comment]
@felipeblazing  They should all be using the same memory resource, at least for GPU. We will need to think about how we do that for other resources. Additionally after implementing a per query batch job executor, we can extend the concept into a global job executor. The global job executor could have policies that help sort jobs based on what query they come from.
