### ISSUE TITLE
Removing global locks when calling pure C functions

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#842]

**Comment by felipeblazing** [comment]
The look at the code in https://github.com/BlazingDB/blazingsql/blob/branch-0.15/engine/bsql_engine/io/io.pyx and find all the functions that are cdef only. Those functions are calling only c apis. Any code that calls c apis should be inside of a 
with nogil: 

and nogil must be added to the c api that it is calling defined in 
https://github.com/BlazingDB/blazingsql/blob/branch-0.15/engine/bsql_engine/io/cio.pxd

None of our c apis modify python classes in a non thread safe manner so we can always release the gil.
