### ISSUE TITLE
[BUG] Using create_table with wildcards crashes kernels 

### ISSUE THREAD

**Issue by poopoothegorilla** [BlazingDB/blazingsql#857]
**Describe the bug**
When using wildcards in the `create_table` method the kernel crashes.

**Steps/Code to reproduce bug**
1. log into https://app.blazingsql.com/ for a free notebook session
2. put multiple parquet files with the same schema in an S3 bucket with hive partitioning scheme (date_partition). 
3. run the following code on a stable release

```python
#!/usr/bin/env python
# coding: utf-8
from blazingsql import BlazingContext
bc = BlazingContext(pool=True,enable_logging=True)
bc.s3('test', 
      bucket_name='------------', 
      access_key_id='-------------', 
      secret_key='----------------',
    region='us-east-1')
bc.create_table('process_events', 's3://test/process_events/date_partition=*/*.0.9.parquet')
```

4. An error occurs when creating the table and crashes the kernel.

**Expected behavior**
The code should successfully create a table.

**Environment overview (please complete the following information)**
 - Environment location: https://app.blazingsql.com/

**Environment details**
everything is on the stable release on  https://app.blazingsql.com/ free notebooks

**Additional context**
- slack conversation with blazingSQL team https://rapids-goai.slack.com/archives/CHAMR5NGZ/p1594132013087000
- creating a list of all the static file locations and passing them into the create_table method does work without kernel failure.

**----For BlazingSQL Developers----**
**Suspected source of the issue**
Where and what are potential sources of the issue

**Other design considerations**
What components of the engine could be affected by this?

**Comment by williamBlazing** [comment]
We currently don't support wildcards in directories for s3 filesystems. 
Short term, we need to provide an appropriate error message to indicate this lack of support and in the long term, this is something we will be able to support.

**Comment by felipeblazing** [comment]
@aucahuasi I think what we should here is add an api to all of the file system providers that is of the nature?

supports_multiple_wildcard() 

if the file system supports using multiple wild cards it returns true, if not it returns false. Then when we can validate the query for the filesystem. If the filesystem does not support multiple wild cards but the path it was given has multiple wildcards we should return an error letting the user know that we dont support multiple wild cards on that filesystem
