### ISSUE TITLE
[BUG] Wrong results on TPCH 01

### ISSUE THREAD

**Issue by rommelDB** [BlazingDB/blazingsql#859]
**Describe the bug**
The single-node SF1 validation reports:

```
AssertionError: DataFrame.iloc[:, 2] (column name="sum_qty") are different

DataFrame.iloc[:, 2] (column name="sum_qty") values are different (75.0 %)
[left]:  [37734107.0, 991417.0, 74476040.0, 37719753.0]
[right]: [37723424.0, 991417.0, 74415660.0, 37708296.0]
```

**Comment by williamBlazing** [comment]
For an aggregation of a float its not always expected to be exactly the same. Can you provide more context? Please provide the query and the data types. This may be a non-issue and may just be getting validated expecting exact values, instead of close enough

**Comment by rommelDB** [comment]
@williamBlazing Sure, the query is as follows:

```
	query ="""
		select
			l_returnflag,
			l_linestatus,
			sum(l_quantity) as sum_qty,
			sum(l_extendedprice) as sum_base_price,
			sum(l_extendedprice*(1-l_discount)) as sum_disc_price,
			sum(l_extendedprice*(1-l_discount)*(1+l_tax)) as sum_charge,
			avg(l_quantity) as avg_qty,
			avg(l_extendedprice) as avg_price,
			avg(l_discount) as avg_disc,
			count(*) as count_order
		from
			lineitem
		where
			l_shipdate <= date '1998-12-01' - interval '90' day
		group by
			l_returnflag,
			l_linestatus
		order by
			l_returnflag,
			l_linestatus
	"""
```

The column l_quantity is of type float, but some sample values are:
```
idx | l_quantity |  
1 | 17.0 |  
2 | 36.0 |  
3 | 8.0 |  
4 | 28.0 |  
5 | 24.0 |  
```

It is too big to consider it as a precision error.

**Comment by williamBlazing** [comment]
For the data types that are floats that are being aggregated that are actually whole numbers encoded as floats, please cast them integers and see if the problem persists. Otherwise we can assume that the differences we are seeing are due to rounding errors with aggregating floats which are expected

**Comment by rommelDB** [comment]
Query passes by casting all floating-point columns to double explicitly, Closing since the source issue is #874 @williamBlazing @Christian8491
