### ISSUE TITLE
[BUG] Crash on TPCH 16

### ISSUE THREAD

**Issue by rommelDB** [BlazingDB/blazingsql#862]
**Describe the bug**
The engine crashes running TPCH 15:

```
blazingsql/engine/src/execution_graph/logic_controllers/BatchJoinProcessing.cpp:92: void ral::batch::split_inequality_join_into_join_and_filter(const string&, std::__cxx11::string&, std::__cxx11::string&): Assertion `tree.root().type == ral::parser::node_type::OPERATOR' failed.
blazingsqlonly-sources-0807/blazingsql/engine/src/execution_graph/logic_controllers/BatchJoinProcessing.cpp:92: void ral::batch::split_inequality_join_into_join_and_filter(const string&, std::__cxx11::string&, std::__cxx11::string&): Assertion `tree.root().type == ral::parser::node_type::OPERATOR' failed.
distributed.nanny - WARNING - Restarting worker
```

**Comment by rommelDB** [comment]
This issue should be fixed after merging the PR #826 .

**Comment by williamBlazing** [comment]
@rommelDB PR #826 has been merged. Please see if this issue is now resolved

**Comment by rommelDB** [comment]
@williamBlazing I'm afraid that as Cristian previously pointed out, many times the application of this operator is not viable. For TPCH 16 I got:

`
[11:04:01.189] [error] 1409356280|15|15|In PartwiseJoin kernel left_idx[0] right_ind[0] for PartwiseJoin(condition=[true], joinType=[inner]). What: cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1594169229136/work/cpp/src/filling/repeat.cu:145: The resulting table has more rows than size_type's limit.|||||
`

We will have to try to optimize the logical plan via Calcite.

**Comment by rommelDB** [comment]
Replacing the implicit join by an explicit one, the query passes SF1.
