### ISSUE TITLE
ability to import a sql database along with .csv and other file formats

### ISSUE THREAD

**Issue by nbarotnvidia** [BlazingDB/blazingsql#865]
A lot of structured large scale simulators will have an option to save simulation results in sql database files.
The current APIs of Blazing SQL operate on csv or other file formats which are not native sql database files, make one to export the database using dump2csv features of some database browsers. 

This creates 2 problems. 
1) increases overall latency to ingestion of data due to invocation of sqldb export step.
2) defeats the acceleration provided by RAPIDS as a multi 100GB db monster needs to be first converted to CSV files and  one has to create many tables again in BlazingContexts()  from the ingested CSV files ...

Currently most of the 'sqlbroswer' type open/community tools are not GPU accelerated, and becomes a bottleneck in using rapids.ai infrastructure

**----For BlazingSQL Developers----**
**How and where should this be implemented?**
What part of the code should be feature be implemented? What should the APIs and/or classes look like?

**Other design considerations **
What components of the engine could be affected by this? What functions should we make sure we use/reuse?

**Testing considerations?**
What sort of unit tests and/or End to End tests be implemented to test this?

**Comment by felipeblazing** [comment]
We have added support for postgres, mysql and sqlite.
