### ISSUE TITLE
[BUG] Installation Issue

### ISSUE THREAD

**Issue by saifamp** [BlazingDB/blazingsql#888]
I have tried installing blazingsql on a few gpu instances in aws. Everytime I installed RAPIDs stack and then went on to install the blazingsql with the following command:

 ```
conda install -c blazingsql/label/cuda10.2 -c blazingsql -c rapidsai -c  \ 
nvidia -c conda-forge -c defaults blazingsql python=3.7
``` 

Everytime I do so, the installation keeps waiting and waiting till I have to kill it. Is there any dependency clash between the two ecosystems?

I am installing the RAPIDs stack as:

```
conda install -c rapidsai -c nvidia -c conda-forge   -c defaults \
 rapids=0.14 python=3.7 cudatoolkit=10.2
```

Thanks.

**Comment by romulo-auccapuclla** [comment]
@saifamp thanks for submitting this issue, in order to continue with the review please can you provide the following details:
- os version where are you running the command
- nvidia-smi command output
- aws gpu instance type where you are installing blazingsql
- conda version

**Comment by saifamp** [comment]
Here are the outputs:

os version: 
```
Ubuntu 16.04
```

nvidia-smi:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   44C    P8    15W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

AWS gpu instance type:
```
g4dn.4xlarge
```

conda version:
```
conda 4.5.11
```

**Comment by williamBlazing** [comment]
@saifamp One potential issue is that the machine you are using has CUDA 10.1 and the stack you are installing is for CUDA 10.2

Also, what libraries from RAPIDS are you going to be using? Installing BlazingSQL will also install `cudf`. You may want to try installing BSQL first and then any other RAPIDS libraries you need
