### ISSUE TITLE
[BUG] Did something happen to `count(*)`?

### ISSUE THREAD

**Issue by roaramburu** [BlazingDB/blazingsql#895]
**Describe the bug**
The SQL function `count(*)` seems to have had a performance regression. For a query that used to run in 285 ms now runs in 4.6 seconds. I'm wondering if we might have lost improvements somewhere.

**Steps/Code to reproduce bug**
```
from blazingsql import BlazingContext

bc = BlazingContext()

bc.s3('blazingsql-colab', bucket_name='blazingsql-colab')

bc.create_table('big_taxi', 's3://blazingsql-colab/yellow_taxi/1_0_0.parquet')

bc.sql('select count(*) from big_taxi')
```

**Environment details**
Ran on BSQL Notebooks RAPIDS Stable

**----For BlazingSQL Developers----**
**Suspected source of the issue**
Where and what are potential sources of the issue

**Other design considerations**
What components of the engine could be affected by this?

**Comment by roaramburu** [comment]
```print(bc.explain('select count(*) from big_taxi'))
LogicalAggregate(group=[{}], EXPR$0=[COUNT()])
  LogicalProject($f0=[0])
    BindableTableScan(table=[[main, big_taxi]], projects=[[]], aliases=[[$f0]])```

**Comment by rommelDB** [comment]
@roaramburu I just found the source of the regression. I'll create a PR soon.
