### ISSUE TITLE
[FEA] Support "create table as select" (CTAS) statements

### ISSUE THREAD

**Issue by randerzander** [BlazingDB/blazingsql#896]
I would like to register new tables as the result of a select statement:
```
create table new_table as select * from existing_table
```

**Comment by williamBlazing** [comment]
@randerzander We have no short term plans for supporting DDL function in BlazingSQL. All DDL type functions in the short term will be pythonic.
What you want to do in a pythonic fashion would be done as follows:
`bc.create_table('new_table', bc.sql('select * from existing_table') )`

**Comment by williamBlazing** [comment]
For now I am closing this issue, if you wish to continue discussing this feature, feel free to reopen it.
