### ISSUE TITLE
[DOC] update os support info

### ISSUE THREAD

**Issue by roaramburu** [BlazingDB/blazingsql#899]
## Report incorrect documentation

We need to list out all supported builds and Cuda drivers. We should look into github badges off the gpuci results for github. 

**Location of incorrect documentation**
Provide links and line numbers if applicable.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

**Comment by williamBlazing** [comment]
Support matrix is: centOS, ubuntu 16, 18, python 3.7, 3.8, cuda 10.1, 10.2

Also try to add github badges
