### ISSUE TITLE
[FEA] Support "lead" and "lag" functions

### ISSUE THREAD

**Issue by randerzander** [BlazingDB/blazingsql#905]
Related to #108

Given BlazingSQL's integration with dask_cudf, users can implement [lag](https://stackoverflow.com/questions/58665010/sql-shift-column-down-1-row) equivalent logic with Dask DataFrame's `shift` function:
```
sql = """
select * from myTable
"""

ddf = bc.sql(sql)
ddf['lagged'] = ddf.shift(periods=1)
bc.create_table('myTable_lagged', ddf)
```

but it would be nice to have native SQL `lag` and `lead` functionality.

**Comment by williamBlazing** [comment]
LAG and LEAD and window functions, and will likely be some of the first window functions that will be implemented

**Comment by williamBlazing** [comment]
this has been implemented for most cases
