### ISSUE TITLE
Create unit test for Project Kernel

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#908]
- First a mock of the class `ral::cache::graph` needs to be created. The only function that needs to work in that mock is `get_estimated_input_rows_to_kernel`. You should be able to configure the output of that function in the creation of the mock.

- Create multiple unit tests of the Project Kernel where you feed data to the input CacheMachine. Run the project kernel and validate the output.

- Create additional test cases where the inputs into the CacheMachine are added with a time delay, so that they are not all present then the test starts. Make utilities that are reusable for this so that other unit tests for other kernels can do similar types of tests. 

- Also make sure that we test the edge case of empty input data

**Comment by williamBlazing** [comment]
We want to have a utility function that can feed an input cache with time delays. The function can have an API like this:
void add_data_to_cache_with_delay(std::shared_ptr<CacheMachine> cache_machine, std::vector<std::unique_ptr<BlazingTable>> data_in, std::vector<int32> delays_in_ms)

Internally this function would launch a detached thread that adds these data_in into the cache_machine and then waits on its corresponding delay. This function would end by calling `cache_machine->finish()`

**Comment by Christian8491** [comment]
It was already implemented with this PR https://github.com/BlazingDB/blazingsql/pull/939
