### ISSUE TITLE
[QST] Reading Single Large Parquet file using dask and  blazing supported  

### ISSUE THREAD

**Issue by VibhuJawa** [BlazingDB/blazingsql#92]
**What is your question?**
Is reading single large file parquet file (gt> GPU memory) using (dask and  blazing) supported  currently ? 

I am currently run into OOM issues when i try to read a single large parquet file into a table using blazing sql .

**Comment by aucahuasi** [comment]
Hi @VibhuJawa thanks, excellent question. Currently we are working on that. I'm sure @felipeblazing can give us more details here +1

**Comment by felipeblazing** [comment]
You will have to read it in with dask dask_cudf.read_parquet then you create a table from that dask data_frame. Right now if it makes more than one partition per worker there are issues. If it makes one partition per worker it works fine. The file itself isn't what has to fit into the GPU but rather the columns that are being operated on.

**Comment by felipeblazing** [comment]
Can you show us what the query  looks like?

**Comment by VibhuJawa** [comment]
> You will have to read it in with dask dask_cudf.read_parquet then you create a table from that dask data_frame. Right now if it makes more than one partition per worker there are issues. If it makes one partition per worker it works fine. The file itself isn't what has to fit into the GPU but rather the columns that are being operated on.

Thanks for the clarification. I guess then i need to find a way to make `dask_cudf.read_parquet` read  a single file into multiple partitions which currently does not seem to be supported. 

At least from the docs it seems that there will be 1 single large file per partition. 

FYI:

https://stackoverflow.com/questions/58437182/how-to-read-a-single-large-parquet-file-into-multiple-partitions-using-dask-dask

**Comment by felipeblazing** [comment]
A single file is not a problem for dask what is a problem for dask is a single file wiht a single row group. If the file is large and has a single row group  then that is really a problem in how the row group was generated. For thigns like blazing and dask to be able to really take advantage of things we need files to have multiple row groups when they are large. This gives us a way of not only dividing computation but also a way of being able to skip over data using meta data for those row groups.

**Comment by williamBlazing** [comment]
@VibhuJawa We just merged in a PR for our skip-data implementation, which can filter out row-groups based on Parquet metadata. Additionally, it can now distributed based on rowgroups as opposed to just files. The next thing we will be working on will be Bigger Than GPU processing, where we will be able to break up queries even further, at which point we should not have any limitation for how large parquet files are.
