### ISSUE TITLE
[BUG] create_table should detect when incorrect parameters are passed to it

### ISSUE THREAD

**Issue by gumdropsteve** [BlazingDB/blazingsql#922]
**Describe the bug**
`columns` arg accepted by `.create_table()` but does nothing. Updating to `names` works, but maybe `columns` should throw an error or be an alias.
![image](https://user-images.githubusercontent.com/43570913/89341652-7663b980-d656-11ea-9777-b19353a52e9e.png)

**Steps/Code to reproduce bug**
https://gist.github.com/gumdropsteve/fc1591290a5036c1a04e66e3ee2341ef

**Expected behavior**
`columns` arg to either set column names or throw error.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
[app.blazingsql.com](https://app.blazingsql.com)

**Comment by williamBlazing** [comment]
The issue is not that columns does nothing or that it should be an alias. The issue is that `create_table` should indicate when you give it the wrong parameter. `columns` is not a parameter

**Comment by williamBlazing** [comment]
We need to add validation that the parameter arguments are correct and of the correct type (everything that is handled by kwargs)  of all the main user APIs:
`BlazingContext`
`bc.sql`
`bc.create_table`
`bc.s3`
`bc.hdfs`
`bc.gs`
