### ISSUE TITLE
add configurable log level

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingsql#953]
right now logging is impacting run time and theres no way to prevent that. We should wrap our logging statements in some kind of macro that lets us turn it on and off depending on levels set. Right now we only have something like that for flushing

**Comment by williamBlazing** [comment]
I suggest implementing this by configuring spdlog. 
We currently configure the `spdlog::flush_on`  using a `config_option` = `LOGGING_LEVEL`.
We should do something similar for `file_sink->set_level`  as soon here https://github.com/BlazingDB/blazingsql/blob/branch-0.15/engine/src/cython/initialize.cpp#L76

I think we should rename the current `LOGGING_LEVEL` to `LOGGING_FLUSH_LEVEL`, and use `LOGGING_LEVEL` to control `file_sink->set_level`.

I also think we should leave alone the `stdout_sink->set_level(spdlog::level::err);` `https://github.com/BlazingDB/blazingsql/blob/branch-0.15/engine/src/cython/initialize.cpp#L68`
