### ISSUE TITLE
Implement bc.list_tables() and bc.describe_table(table_name)

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#954]
Look into what calcite returns for DDL... 
update apache calcite does not support DDL out of the box. See here https://calcite.apache.org/docs/adapter.html#server

**Comment by williamBlazing** [comment]
`bc.list_tables()` should return a list of all the names of the tables that have been created

`bc.describe_table(table_name)` should return the names of all the columns and their types for the specified table. If that table name is not found it should throw an appropriate error

**Comment by roaramburu** [comment]
hey @williamBlazing what's the syntax then? do we have docs on this?
