### ISSUE TITLE
Build Docker Nightly after Code Merge

### ISSUE THREAD

**Issue by roaramburu** [BlazingDB/blazingsql#976]
**Is your feature request related to a problem? Please describe.**
We are not building the bsql nightly version for docker, we need to be doing that.

**----For BlazingSQL Developers----**
**How and where should this be implemented?**
What part of the code should be feature be implemented? What should the APIs and/or classes look like?

**Other design considerations **
What components of the engine could be affected by this? What functions should we make sure we use/reuse?

**Testing considerations?**
What sort of unit tests and/or End to End tests be implemented to test this?

**Comment by williamBlazing** [comment]
this seems like a duplicate issue https://github.com/BlazingDB/blazingsql/issues/616

**Comment by williamBlazing** [comment]
duplicate
