### ISSUE TITLE
UX Log rotation (spdlog)

### ISSUE THREAD

**Issue by aucahuasi** [BlazingDB/blazingsql#978]
So we avoid to have big logs

**Comment by roaramburu** [comment]
What does that mean? Log rotation?

**Comment by williamBlazing** [comment]
What do you need? you want to keep log file size smaller per file? so, maybe write to a new file per day? or you want to re-use files to keep aal disk consumption of logs small?

**Comment by aucahuasi** [comment]
The 1st one, in general we need to ensure for a cluster setup:
- In case a user needs to have the log is better to send them the latest one and not a very big file of log.
- In case we want to get all the logs from start_date to end_date it should be possible (in this case it should be easy to switch to a centralized log system)

**Comment by roaramburu** [comment]
i think having the logs consistently append is fine. they'll be able to query those logs w/ bsql which should make it manageable. how big do the log files get?

to not let them see all logs is going to be an issue. we'll need to move to centralized logging longer term so that they can see everything they have run from a single UI i believe.

**Comment by aucahuasi** [comment]
>i think having the logs consistently append is fine. they'll be able to query those logs w/ bsql which should make it manageable. >how big do the log files get?

A log file can easily go up to 300mb, that would be a bad UX not only for a user but also for an engineer who is trying to know what happened. I think we should not use our bc.log for a cluster in production, is better to rely on an external log system for such deployments.

>to not let them see all logs is going to be an issue. we'll need to move to centralized logging longer term so that they can see >everything they have run from a single UI i believe.

Yeah this would be ideal for a distributed cluster use case, I know we can use spdlog, log4j and pylog so they all push the logs into a single log server ... and all of this stuff can be optional

**Comment by williamBlazing** [comment]
spdlog, should have options that allow us to do this. So we should try to use those features.

We could also set the default logging level to be less verbose.

We could also disable the other logs by default as well (the ones that were made for the visualizer) cc @felipeblazing

**Comment by felipeblazing** [comment]
We should not use spdlog in all frankness. The fact that we are using it is screwing us and hard. The data is saved as text, gross it should be some compact binary format. That alone could save a ton of space.  They also need to be flushed and the default log level needs to be MUCH more quiet than it currently is.

**Comment by williamBlazing** [comment]
Can you explain this: `The fact that we are using it is screwing us and hard. ` 

Making the logs be binary will make them a lot harder to consume. If you're worried about space than we can just simply overwrite them every so often or something like that but there are lots of other ways of ameliorating a lot of your concerns without completely getting rid of the framework

**Comment by williamBlazing** [comment]
Here is how to setup rotating logs:
https://github.com/gabime/spdlog#rotating-files

**Comment by felipeblazing** [comment]
I mean that the format in which its currently stored is much less efficient than something like parquet and orc. And in all honesty if they are using blazing anyway then they can view the files pretty easily with select * from logs in the engine itself. If someone wants to view it as CSV we can let them export that.
