### ISSUE TITLE
UX BlazingConfig hasmap should always read from context vars first

### ISSUE THREAD

**Issue by aucahuasi** [BlazingDB/blazingsql#979]
So the user have more flexibility to manage the conf

**Comment by roaramburu** [comment]
Also don't know what this issue means.

**Comment by williamBlazing** [comment]
...., yeah what does this mean?

**Comment by aucahuasi** [comment]
It means that the user can setup the blazing config map by just exporting env vars, this give any cluster user the flexibility to the choose dir location for the cache and the logs and thus avoid to wrtite
```python
blzconf={}
blzconf["log_dir"]="/asdasd/asda/sd/"
blzconf["cache_dir"]="/fghfgdh/fhfdghf/fgh"
bc = Blazingcontext(blzconf)
```
If we allow the user to define these settings as env vars as default then the cluster user would need to do only
```python
bc = Blazingcontext()
```
and that's all!

**Comment by roaramburu** [comment]
right now they are able to run `bc = BlazingContext()` without arguments, correct?

is that not the case?

**Comment by aucahuasi** [comment]
Yes, but the default config options are hardcoded instead of take those options from env vars ... for example not all clusters will want to use the cache dir in the /tmp folder and not everyone will want to write boilerplate code just for that.

**Comment by williamBlazing** [comment]
so, you want to be able to set the config options via environment variables, aside from the `config_options` parameter?
