### ISSUE TITLE
Error messages to connect to S3 and GS

### ISSUE THREAD

**Issue by kharoc** [BlazingDB/blazingsql#987]
When I execute, for example :

`bc.s3(authority, bucket_name=bucket_name, encryption_type=S3EncryptionType.NONE, access_key_id=access_key_id, secret_key=secret_key)`

The connection is successful but it showed in console the next message. And it seems that there is an error.

` 2020-09-01T11:33:11Z|2110168128|TRACE|deregisterFileSystem: filesystem authority not found. `

**Comment by felipeblazing** [comment]
This may not be an nissue

```
2020-09-01T11:33:11Z|2110168128|TRACE|deregisterFileSystem: filesystem authority not found.

```
Is probably an error message that shows up because it tries to deregister the filesystem in case it existed before this. We could clean it up by not throwing an error if it didnt exist before but its not a big concern

**Comment by Christian8491** [comment]
This was really not an error connection. It was removed fro the PR #1068
