### ISSUE TITLE
Ensure we can run 30/30 in one go with existing

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#991]
ran 1-17 with allocator = default
all queries using persist() and `del`s
got hung up on 18. also has prints for bc.get_free_memory at the beginning of 1-13 and it did not seem to show any leaks

Examining the logs they only contain six queries. The last one was Q3 Q3 had an out of memory error during an order buying merge which allowed all the other nodes to finish successfully but Q3 did not finish and therefore it actually errored silently. We don't know why it didn't have any more of the logs

**Comment by Christian8491** [comment]
ran 1-26 with` allocator = existing`
all queries using `persist()` and `del` S
Query 08 crashed.
Query 27 crashed -->  https://github.com/rapidsai/tpcx-bb/blob/main/tpcx_bb/queries/q27/tpcx_bb_query_27_sql.py#L47  (nlp = 
      spacy.load("en_core_web_sm")
Quuery 28 currently have issues. (had to test isolated to succeed)

**Comment by Christian8491** [comment]
Updating:
Ran `29/30` using `allocator=existing` (waiting for q28)
Queries 10, 18 ,19 now are using ORDER BY instead of  bc.partition()
