### ISSUE TITLE
[QST]  SQL on Dask

### ISSUE THREAD

**Issue by kyprifog** [BlazingDB/blazingsql#996]
Is it appropriate to use this library if you wanted to just get a SQL interface over the top of normal (CPU based) Dask dataframes?   Are there any better alternatives for that simple use case?

**Comment by roaramburu** [comment]
Hey @kyprifog, we are effectively a SQL interface on Dask, but work for Dask GPU Dataframes. That being said we are able to run queries directly on pandas dataframes, so it's possible we work on (CPU based) Dask dataframes, but you would need to have a GPU for BlazingSQL.

If you test out BSQL on on cpu based dask dataframes please let us know here as we would love to hear about that.

There is an incredibly new project that just came out that does SQL on Dask (CPU), I can't find the link to it right now.

Thanks!

**Comment by kyprifog** [comment]
@roaramburu thanks!  If you find the name of that other project please let me know I would like to check it out as well.

**Comment by martindurant** [comment]
See https://github.com/nils-braun/dask-sql
